Adding missing command for imported SSL certs.
uyuni-project/uyuni-docs pull request #1005
Opened 2021-06-22 08:34 UTC by 0rnela

# Description

Missing instruction in the Procedure: Replacing Existing Certificates.

# Target branches

Which documentation version does this PR apply to?

- [x] Master (Default)
- [ ] Manager-4.2
- [ ] Manager-4.1
- [ ] Manager-4.0

# Links

Fixes https://github.com/uyuni-project/uyuni/issues/3808

2021-06-22 08:45 UTC, mcalmer requested changes

2021-06-22 08:45 UTC, mcalmer commented on modules/administration/pages/ssl-certs-imported.adoc
> +----
We generated an RPM so we need to install it. We described it in "ssl-certs-selfsigned". So maybe something like this?

```suggestion
. Install the RPM that contains the newly generated certificate.
    Check that you have the latest version of the RPM before running this command.
    The version number is incremented every time you re-create the certificates.
+
----
rpm -Uhv /root/ssl-build/sumahostname/rhn-org-httpd-ssl-key-pair-sumahostname-1.0-2.noarch.rpm
----
. Restart services to pick up the changes:
+
----
spacewalk-service restart
----
```

2021-06-23 10:43 UTC, jcayouette approved these changes

2021-07-05 12:02 UTC, keichwa approved these changes

2021-07-05 12:02 UTC, keichwa commented on modules/administration/pages/ssl-certs-imported.adoc
> +    Check that you have the latest version of the RPM before running this command.
For optical reasons, we want just 2 spaces here.
```suggestion
  Check that you have the latest version of the RPM before running this command.
```

2021-07-05 12:04 UTC, keichwa commented
Ornela, maybe it is worth adding a sentence to the top-level `.changelog` file.

2021-07-05 12:59 UTC, mcalmer approved these changes

2021-07-07 07:58 UTC, merged