Salt package lock #15572 keichwa
uyuni-project/uyuni-docs pull request #1130
Opened 2021-08-26 14:34 UTC by keichwa

# Description

https://github.com/SUSE/spacewalk/issues/15572

# Target branches

Which documentation version does this PR apply to?

- [x] Master (Default)
- [x] Manager-4.2

# Links

Fixes #<insert issue or PR link, if any>

2021-08-29 09:08 UTC, mcalmer requested changes
Btw: There is one big difference between package lock with zypp and the others.
With zypp you can also lock packages which are not installed. This prevent installing the the package. This is not possible for RHEL or Debian like systems. They can only lock packages which are installed.
Our UI reflect this, we we show only installed packages for RHEL and Debian like systems while for SUSE systems we show all available packages.

2021-08-29 09:08 UTC, mcalmer commented on modules/client-configuration/pages/registration-bootstrap.adoc
> +On {rhel}-like systems (version 7), you must have the [package]``yum-plugin-versionlock`` package installed.
On RHEL 8 locking is supported as well. The plugin package is named a bit different:

  python3-dnf-plugin-versionlock

2021-08-29 09:08 UTC, mcalmer commented on modules/client-configuration/pages/registration-bootstrap.adoc
> +On {rhel}-like systems (version 7), you must have the [package]``yum-plugin-versionlock`` package installed.
And Debian/Ubuntu is supported as well. `apt` has the support included.

2021-09-15 14:06 UTC, keichwa commented
> Btw: There is one big difference between package lock with zypp and the others.
> With zypp you can also lock packages which are not installed. This prevent installing the the package. This is not possible for RHEL or Debian like systems. They can only lock packages which are installed.
> Our UI reflect this, we we show only installed packages for RHEL and Debian like systems while for SUSE systems we show all available packages.

Thanks for input, @mcalmer --I hope I addressed all your concerns.  Can you please review again?

2021-09-15 15:46 UTC, mcalmer approved these changes
LGTM

2021-09-15 16:01 UTC, vzhestkov approved these changes
Looks good

2021-09-15 16:30 UTC, keichwa commented
Thanks for your approvals, Michael and Victor!  Now, @0rnela / @jcayouette I need at least one tic of my co-editors, too ;)

2021-09-16 08:47 UTC, 0rnela approved these changes

2021-09-16 08:56 UTC, merged