Document Debian 11
uyuni-project/uyuni-docs pull request #1136
Opened 2021-08-31 10:16 UTC by juliogonzalez

# Description

Document Debian 11

# Target branches

Which documentation version does this PR apply to?

- [x] Master (Default)
- [x] Manager-4.2
- [ ] Manager-4.1
- [ ] Manager-4.0

# Links

https://github.com/SUSE/spacewalk/issues/15683

2021-09-01 09:11 UTC, keichwa submitted a review, later dismissed

2021-09-01 09:11 UTC, keichwa commented on .changelog
> +- Document Debian 11 as a supported OS as a client
```suggestion
- Documented Debian 11 as a supported OS as a client in Client
  Configuration Guide
```
[According to the recipe above.  We probably should review our recipes...]

2021-09-02 06:54 UTC, keichwa commented
@juliogonzalez do you have commit rights?  Or is this still WIP?  If it is WIP, we'd better convert it to "draft mode"--there is this option in the "Reviewers" section.

2021-09-02 08:09 UTC, juliogonzalez commented
@keichwa this is still WIP, I am still testing Debian11 so this is not ready to be merged.

2021-12-03 12:08 UTC, juliogonzalez commented
Ready to be reviewed. Sorry for not adding the render of the doc, but (at least today), GitHub is rejecting .zip and .tar.gz files, and other compression formats are not accepted :(

2021-12-09 12:02 UTC, jcayouette approved these changes

2021-12-09 12:06 UTC, jcayouette requested changes
Could we split this content into individual Uyuni/SUMA tables?

We should not use ifdefs inside of our tables as they are known to break occasionally for localized documents. "I still have not figured out why".

It is fine to use conditional statements (ifeval, ifdef) as wrappers but using them inside of a table can cause bugs.

So two tables:

One for suma-content = true

One for uyuni-content= true

Sorry I did not mention this before. This bug was discovered in a localization review from Patrick.

2021-12-09 12:10 UTC, juliogonzalez commented
@jcayouette not on this PR, sorry. I just did what we did in the past.

Besides the tables are huge, so then you need to make sure they are coordinated because the content is almost the same.,

2021-12-09 12:14 UTC, juliogonzalez commented
Can we merge the PR? The code is already merged.

Later you can discuss with your squad how to handle those huge tables. I am not sure not using if/else is the right approach in this case, given the maintenance effort for two tables that will be almost the same. But have a meeting inside the team, discuss it, do the split, and make sure you document it, as otherwise we'll end with unsynced tables when someone updates one, but not the other (even if updates for both are needed).

2021-12-09 12:21 UTC, jcayouette commented
Sure but just know it may break in the localized versions.

2021-12-09 12:22 UTC, jcayouette commented
Technically using a snippet for these supported tables would be best. I need to ping upstream to see why these bits are breaking. It is not always the case.

2021-12-09 12:23 UTC, jcayouette approved these changes
Approved but we need to revisit conditionals in tables at some point.

2021-12-09 12:48 UTC, merged