Update hostname rename documentation
uyuni-project/uyuni-docs pull request #1158
Opened 2021-09-09 11:52 UTC by cbosdo

# Description

Fix the server hostname renaming documentation to match with https://github.com/uyuni-project/uyuni/pull/4204. The 4.2 and 4.1 PRs aren't submitted yet and will be once the original one is approved.

# Target branches

Which documentation version does this PR apply to?

- [X] Master (Default)
- [X] Manager-4.2
- [X] Manager-4.1

2021-09-09 13:02 UTC, jcayouette requested changes
Looks good, however I suggest a minor change to:
 "the time it takes to run depends on the amount of registered Salt systems." to:

"the time it takes to run depends on the **number** of registered Salt systems."

2021-09-09 13:15 UTC, cbosdo commented
> Looks good, however I suggest a minor change to:
> "the time it takes to run depends on the amount of registered Salt systems." to:
> 
> "the time it takes to run depends on the **number** of registered Salt systems."

Fixed now

2021-09-13 13:34 UTC, jcayouette commented
@cbosdo Looks good feel free to merge.

2021-09-13 13:35 UTC, jcayouette approved these changes

2021-09-13 14:34 UTC, merged