[WIP] Adding SLES15 SP3 info to SUMA 4.1 docs
uyuni-project/uyuni-docs pull request #1169
Opened 2021-09-14 14:15 UTC by 0rnela

# Description

Adding information about supporting SLES 15 SP3. 

# Target branches

Which documentation version does this PR apply to?

- [x] Master (Default) https://github.com/uyuni-project/uyuni-docs/pull/1166
- [x] Manager-4.2 https://github.com/uyuni-project/uyuni-docs/pull/1168
- [x] Manager-4.1
- [ ] Manager-4.0

# Links

Fixes https://github.com/SUSE/spacewalk/issues/15868

2021-09-14 14:17 UTC, jcayouette approved these changes

2021-09-14 15:27 UTC, keichwa approved these changes

2021-09-15 07:06 UTC, jcayouette requested changes
There seems to be an xref error reported on our test run, could you have a look and try and resolve it?

2021-09-16 10:21 UTC, 0rnela commented
@jcayouette - closing this one that is stuck due to toolchain issue, the actual change is covered in https://github.com/uyuni-project/uyuni-docs/pull/1174.

2021-09-16 10:21 UTC, closed without merging