Replaced obsolete patch instruction with update
uyuni-project/uyuni-docs pull request #1332
Opened 2021-12-13 15:45 UTC by digdilem

# Minor update instructions were misleading and inaccurate. 

As mentioned on the uyuni-users mailing list, the old "zypper patch" instructions no longer appear to work. 

This edit attempts to improve upon that whilst still keeping things succinct.

2021-12-14 07:24 UTC, keichwa commented
We probably did not describe clear enough what this section is meant to cover.  Here we really only want tell how the user can apply just (openSUSE) patches.  These are OS security fixes that are independently released from uyuni releases.

Maybe I got it wrong.  Before taking acation, I must check the ML discussion.

2021-12-14 07:33 UTC, digdilem commented
> Here we really only want tell how the user can apply just (openSUSE) patches

But this is the page to **perform a minor upgrade of Uyuni** - it's linked and described as such, so my feeling is that it should really describe the process to upgrade Uyuni - which merely applying patches does not.  

As they were, the process described does not perform a minor upgrade.

I welcome other thoughts from the review.

2021-12-14 09:13 UTC, keichwa commented
Yes, you are not wrong `;)`  Maybe, we should rename the file from "*minor" to "*normal" and give an example such as upgrade from 2021.11 to 2021.12. Maybe, we can also keep the contents of the old file and change the title somehow ("Security fixes inbetween releases", or sth similar).  Yes, we need more opinions.  Or I should really read the MU discussion now...

2021-12-15 14:27 UTC, jcayouette commented on modules/upgrade/pages/server-minor-upgrade-uyuni.adoc
> +. If zypper reports that the Uyuni package won't be upgraded, run that manually:
"If **Zypper** reports that the Uyuni package will not be upgraded, run the following command manually:"

2021-12-15 14:27 UTC, jcayouette requested changes
See comment.

2021-12-15 15:34 UTC, digdilem commented
Thanks for the improved wording @jcayouette  - updated file with your suggestion.

2022-01-10 08:16 UTC, keichwa approved these changes
Still not convinced, but approving nevertheless (it is probably more useful than before).

2022-01-17 14:09 UTC, 0rnela commented
@digdilem, thank you for this PR. Due to recent changes in books organisation, new PR has replaced this one, with your contributions added there.

2022-01-17 14:09 UTC, closed without merging