Added Quick Start.
uyuni-project/uyuni-docs pull request #1336
Opened 2021-12-21 14:13 UTC by 0rnela

# Description

As part of the future cookbook, we need Quick Start guides for installing SUMA Serevr and Proxy.
Quick Start is currently separate book, and follows the existing structure in Uyuni documentation. 

# Target branches

Which documentation version does this PR apply to?

- [x] Master (Default)
- [ ] Manager-4.2
- [ ] Manager-4.1
- [ ] Manager-4.0

# Links

Fixes partially https://github.com/SUSE/spacewalk/issues/12021

2021-12-21 19:36 UTC, keichwa requested changes
BTW, I did not read all the texts displayed as new or additions.  I assume these are basically file renames or sth. like that.

2021-12-21 19:36 UTC, keichwa commented on modules/quickstart/pages/quickstart-install-suma-proxy.adoc
> +tory for the {productname} Proxy installation.
```suggestion
    [systemitem]``Basesystem``, [systemitem]``SUSE Manager Proxy``, and [systemitem]``Server Applications`` are pre-selected and mandatory for the {productname} Proxy installation.
```
Beware of cats conquering your keyboard `;-)`

2021-12-21 19:36 UTC, keichwa commented on modules/quickstart/pages/quickstart-install-suma-proxy.adoc
> +:[Next].
```suggestion
    OPTIONAL: In the following [guimenu]``Add On Product`` screen, select any additional or add-on products you require, and click btn:[Next].
```
again `;)`

2021-12-22 07:54 UTC, keichwa approved these changes

2021-12-22 12:52 UTC, jcayouette approved these changes

2021-12-22 13:30 UTC, merged