Merged non-SUMA topics to separate book
uyuni-project/uyuni-docs pull request #1337
Opened 2021-12-21 15:03 UTC by 0rnela

# Description

Topics that are either not solely functionalities of SUMA or are complex, but do not belong to any of the existing books, have been moved in Specialized Guides.

# Target branches

Which documentation version does this PR apply to?

- [x] Master (Default)
- [ ] Manager-4.2
- [ ] Manager-4.1
- [ ] Manager-4.0

# Links

Fixes #<insert issue or PR link, if any>

2021-12-21 18:33 UTC, keichwa requested changes

2021-12-21 18:33 UTC, keichwa commented on .changelog
> +  either not bespoke SUMA functionalities, or do not beling in any
```suggestion
  either not bespoke SUMA functionalities, or do not belong in any
```

2021-12-21 18:33 UTC, keichwa commented on modules/specialized-guides/pages/specialized-guides-overview.adoc
> +You can read specialirzed guides for:
```suggestion
You can read specialized guides for:
```

2021-12-22 07:53 UTC, keichwa approved these changes

2021-12-22 12:54 UTC, jcayouette approved these changes

2021-12-22 13:44 UTC, merged