[WIP] Brand new content for Pay-as-you-go
uyuni-project/uyuni-docs pull request #1382
Opened 2022-01-24 17:39 UTC by 0rnela

# Description
Document describes the setup of Pay-as-you-go on the SUSE Manager / Uyuni server.

# Target branches

Which documentation version does this PR apply to?

- [x] Master (Default)
- [x] Manager-4.2
- [ ] Manager-4.1
- [ ] Manager-4.0

# Links

Fixes [#<insert issue or PR link, if any>](https://github.com/SUSE/spacewalk/issues/16273)

2022-01-25 12:32 UTC, 0rnela commented
file:///home/ornela/github/uyuni-docs/build/en/pdf/suse_manager_installation-and-upgrade_guide.pdf

2022-01-25 12:35 UTC, 0rnela commented
[suse_manager_installation-and-upgrade_guide.pdf](https://github.com/uyuni-project/uyuni-docs/files/7933569/suse_manager_installation-and-upgrade_guide.pdf)

2022-01-25 12:39 UTC, 0rnela commented
[uyuni_installation-and-upgrade_guide.pdf](https://github.com/uyuni-project/uyuni-docs/files/7933590/uyuni_installation-and-upgrade_guide.pdf)

2022-01-25 15:56 UTC, keichwa requested changes
Some cosmetic suggestions (according to the wording we use otherwise).  I hope I got it right.

2022-01-25 15:56 UTC, keichwa commented on .changelog
>  - removed end of life caasp references from documentation
```suggestion
- Added instructions for Pay-as-you-go to Installation Guide
- Merge translations of Installation and Upgrade Guide into the new
  combind book
- Removed end of life CaaSP references from documentation
```
With drive-by edits

2022-01-25 15:56 UTC, keichwa commented on modules/installation-and-upgrade/pages/connect-payg.adoc
> +* provides customized {payg} product images (eg. SLES, SLES for SAP...)
```suggestion
* provides customized {payg} product images for SLES, SLES for SAP, etc.
```

2022-01-25 15:56 UTC, keichwa commented on modules/installation-and-upgrade/pages/connect-payg.adoc
> +* valid {scc} credentials iare entered in [guimenu]``Admin > Setup Wizard > Organization Credentials``, even they provide only limited access to products
```suggestion
* valid {scc} credentials are entered in menu:Admin[Setup Wizard > Organization Credentials], even they provide only limited access to products
```

2022-01-25 15:56 UTC, keichwa commented on modules/installation-and-upgrade/pages/connect-payg.adoc
> +. In the [guimenu]``Admin > Setup Wizard > {payg}`` click btn:[Add {payg}].
```suggestion
. In the {productname} {webui}, navigate  to menu:Admin[Setup Wizard > {payg}], and click btn:[Add {payg}].
```

2022-01-25 15:56 UTC, keichwa commented on modules/installation-and-upgrade/pages/connect-payg.adoc
> +. In the new screen, click btn:[Create] to add new {payg} connection data
```suggestion
. In the new screen, click btn:[Create] to add new {payg} connection data.
```

2022-01-25 15:56 UTC, keichwa commented on modules/installation-and-upgrade/pages/connect-payg.adoc
> +. In the menu:Add new {payg} data[Username], add the actual username as specified in the cloud
```suggestion
. In the menu:Add new {payg} data[Username], add the actual username as specified in the cloud.
```

2022-01-25 15:56 UTC, keichwa commented on modules/installation-and-upgrade/pages/connect-payg.adoc
> +. In the menu:Add new {payg} data[Key Password], add key passphrase
```suggestion
. In the menu:Add new {payg} data[Password], enter the password.
. In the menu:Add new {payg} data[Key], add the correct instance key.
. In the menu:Add new {payg} data[Key Password], add key passphrase.
```

2022-01-25 15:56 UTC, keichwa commented on modules/installation-and-upgrade/pages/connect-payg.adoc
> +
```suggestion
. In the menu:Add new {payg} data[Bastion Hostame], add the bastion hostname.
. In the menu:Add new {payg} data[Bastion Port], add the bastion port number.
. In the menu:Add new {payg} data[Bastion Username], add bastion the username.
. In the menu:Add new {payg} data[Bastion Password], add bastion password.
. In the menu:Add new {payg} data[Bastion Key], add bastion key.
. In the menu:Add new {payg} data[Bastion Key Password], add bastion key password.

```

2022-01-25 15:56 UTC, keichwa commented on modules/installation-and-upgrade/pages/connect-payg.adoc
> +. Click btn:[Create] to complete adding new {payg} connection data
```suggestion
. To complete adding new {payg} connection data, click btn:[Create].
```

2022-01-25 15:56 UTC, keichwa commented on modules/installation-and-upgrade/pages/connect-payg.adoc
> +E.g. if the instance has {slsa}15 SP1 product installed, {slsa}15 SP2 and {slsa}15 SP3 will be automatically added and shown in [guimenu]``Admin > Setup Wizard > Products``.
```suggestion
For example, if the instance has the {slsa}{nbsp}15 SP1 product installed, {slsa}{nbsp}15 SP2 and {slsa}{nbsp}15 SP3 will be automatically added and shown in [guimenu]``Admin > Setup Wizard > Products``. 
```

2022-01-25 15:56 UTC, keichwa commented on modules/installation-and-upgrade/pages/connect-payg.adoc
> +To monitor the progress of channel syncing in GUI, go to [guimenu]``Software > Channel List > All``.
```suggestion
To monitor the progress of channel syncing in the {webui}, navigate to [guimenu]``Software > Channel List > All``. 
```

2022-01-25 15:56 UTC, keichwa commented on modules/installation-and-upgrade/pages/connect-payg.adoc
> +To monitor the syncing progress in the log files, go to /var/log/rhn/reposync directory on the {productname} server.
```suggestion
To monitor the syncing progress, check the log files in the [path]``/var/log/rhn/reposync`` directory on the {productname} server.
```

2022-01-25 15:56 UTC, keichwa commented on modules/installation-and-upgrade/pages/connect-payg.adoc
> +. You will be returned to the list of instances and the one that was just deleted will no longer be shown
```suggestion
. Navigate to [guimenu]``Admin > Setup Wizard > {payg}``.
. Find the instance on the list of existing instances.
. Click the instance details page.
. Select btn:[Delete] and confirm your selection
. You will be returned to the list of instances and the one that was just deleted will no longer be shown
```

2022-01-25 15:56 UTC, keichwa commented on modules/installation-and-upgrade/pages/connect-payg.adoc
> +Up-to date status of the {payg} instance is shown in the column Status or on the instance details page.
```suggestion
Up to date status of the {payg} instance is shown in the column [guimenu]``Status`` or on the instance details page.
```

2022-01-25 15:56 UTC, keichwa commented on modules/specialized-guides/pages/qs-publiccloud/clients.adoc
> +
```suggestion
For instructions on registering clients on a public cloud, see xref:client-configuration:clients-pubcloud.adoc[].

For instructions on connecting {payg} instances, see xref:installation-and-upgrade:connect-payg.adoc[].

```

2022-01-25 16:40 UTC, 0rnela commented
[suse_manager_installation-and-upgrade_guide.pdf](https://github.com/uyuni-project/uyuni-docs/files/7935457/suse_manager_installation-and-upgrade_guide.pdf)

2022-01-25 16:43 UTC, 0rnela commented
[uyuni_installation-and-upgrade_guide.pdf](https://github.com/uyuni-project/uyuni-docs/files/7935483/uyuni_installation-and-upgrade_guide.pdf)

2022-01-25 18:55 UTC, rjmateus requested changes
Thanks for the great contribution. Some nitpicks do have a look.

2022-01-25 18:55 UTC, rjmateus commented on modules/installation-and-upgrade/pages/connect-payg.adoc
> +. In the menu:Add new {payg} data[Description], add the description of the newly created connection.
payg connection is only created after fields are set and user clicks on create button, after the procedure `proc-finishing-payg-connecting`

2022-01-25 18:55 UTC, rjmateus commented on modules/installation-and-upgrade/pages/connect-payg.adoc
> +. In the menu:Add new {payg} data[Hostname], enter the actual name of the instance as it appears on the cloud.
Field name is `Host`

2022-01-25 18:55 UTC, rjmateus commented on modules/installation-and-upgrade/pages/connect-payg.adoc
> +. In the menu:Add new {payg} data[Username], add the actual username as specified in the cloud.
field name is `User`

2022-01-25 18:55 UTC, rjmateus commented on modules/installation-and-upgrade/pages/connect-payg.adoc
> +. In the menu:Add new {payg} data[Key Password], add key passphrase.
Field name is: `SSH Private Key Passphrase`

2022-01-25 18:55 UTC, rjmateus commented on modules/installation-and-upgrade/pages/connect-payg.adoc
> +. In the menu:Add new {payg} data[Bastion Hostame], add the bastion hostname.
field name is `host`

2022-01-25 18:55 UTC, rjmateus commented on modules/installation-and-upgrade/pages/connect-payg.adoc
> +.Procedure: Adding SSH bastion connection data
The data is added in the page section `Bastion SSH connection data`

2022-01-25 18:55 UTC, rjmateus commented on modules/installation-and-upgrade/pages/connect-payg.adoc
> +.Procedure: Conencting new {payg}  instance
this data is added in the page section `Instance SSH connection data`

2022-01-25 18:55 UTC, rjmateus commented on modules/installation-and-upgrade/pages/connect-payg.adoc
> +. In the menu:Add new {payg} data[Bastion Username], add bastion the username.
field name is `User`

2022-01-25 18:55 UTC, rjmateus commented on modules/installation-and-upgrade/pages/connect-payg.adoc
> +. In the menu:Add new {payg} data[Bastion Key], add bastion key.
Field name is `SSH Private Key`

2022-01-25 18:55 UTC, rjmateus commented on modules/installation-and-upgrade/pages/connect-payg.adoc
> +. In the menu:Add new {payg} data[Bastion Key Password], add bastion key password.
Field name is `SSH Private Key Passphrase`

2022-01-25 18:55 UTC, rjmateus commented on modules/installation-and-upgrade/pages/connect-payg.adoc
> +. You will return to [guimenu]``Admin > Setup Wizard > Pay-as-you-go`` screen.
It will navegate to the PAYG connection data Details page. The update connection status will be displayed on the top section named `Information`

2022-01-25 18:55 UTC, rjmateus commented on modules/installation-and-upgrade/pages/connect-payg.adoc
> +If the invalid data are entered at any point, the newly created instance will be shown in [guimenu]``Admin > Setup Wizard > {payg}``, with column Status displaying error message.
After creation, the detail about the payg ssh connection data will be displayed. 
The status is also displayed in the payg ssh connection data list.

2022-01-25 18:55 UTC, rjmateus commented on modules/installation-and-upgrade/pages/connect-payg.adoc
> +Once the products are shown as available, they need to be scheduled for syncing by selecting the checkbox next to the product name and clicking btn:[Add product].
```suggestion
Once the products are shown as available, the user can add a product to {productname} by selecting the checkbox next to the product name and clicking btn:[Add product].
```

2022-01-25 18:55 UTC, rjmateus commented on modules/installation-and-upgrade/pages/connect-payg.adoc
> +To monitor the progress of channel syncing in the {webui}, navigate to [guimenu]``Software > Channel List > All``.
```suggestion
After the success message user can verify the newly added channels in the {webui}, navigate to [guimenu]``Software > Channel List > All``. 
```

2022-01-25 18:55 UTC, rjmateus commented on modules/installation-and-upgrade/pages/connect-payg.adoc
> +To monitor the syncing progress, check the log files in the [path]``/var/log/rhn/reposync`` directory on the {productname} server.
```suggestion
To monitor the syncing progress of each channel, check the log files in the [path]``/var/log/rhn/reposync`` directory on the {productname} server.
```

2022-01-25 18:55 UTC, rjmateus commented on modules/installation-and-upgrade/pages/connect-payg.adoc
> +The following procedure describes how to delete the instance.
```suggestion
The following procedure describes how to delete ssh connection data to the instance.
```

2022-01-25 18:55 UTC, rjmateus commented on modules/installation-and-upgrade/pages/connect-payg.adoc
> +== Instance status and availability
```suggestion
== Instance credential collect status
```

2022-01-25 18:55 UTC, rjmateus commented on modules/installation-and-upgrade/pages/connect-payg.adoc
> +These credentials are refreshed every 10 minutes by taskomatic, which always uses the last known authentication credentials to access the instance.
```suggestion
These credentials are refreshed every 10 minutes by taskomatic using the defined ssh connection data. Connection to RMT server always uses the last known authentication credentials collected from the payg instance.
```

2022-01-25 18:55 UTC, rjmateus commented on modules/installation-and-upgrade/pages/connect-payg.adoc
> +To delete the instance, use <<proc-deleting-payg-instance>>.
```suggestion
To delete the instance connection data, use <<proc-deleting-payg-instance>>. 
```

2022-01-26 16:16 UTC, rjmateus reviewed
Just some small nitpicks. Thanks For the great work

2022-01-26 16:16 UTC, rjmateus commented on modules/installation-and-upgrade/pages/connect-payg.adoc
> +If you are not connecting directly to the cloud, but via SSH bastion, proceed with <<proc-adding-ssh-bastion-connection-data>>.
```suggestion
If you are not connecting directly to the instance, but via SSH bastion, proceed with <<proc-adding-ssh-bastion-connection-data>>.
```

2022-01-26 16:16 UTC, rjmateus commented on modules/installation-and-upgrade/pages/connect-payg.adoc
> +As soon as the authentication data is available on the server, a list of available products is updated.
```suggestion
As soon as the authentication data is available on the server, the list of available products is updated.
```

2022-01-26 16:16 UTC, rjmateus commented on modules/installation-and-upgrade/pages/connect-payg.adoc
> +For example, if the instance has the {slsa}{nbsp}15 SP1 product installed, {slsa}{nbsp}15 SP2 and {slsa}{nbsp}15 SP3 are automatically added and shown in [guimenu]``Admin > Setup Wizard > Products``.
```suggestion
For example, if the instance has the {slsa}{nbsp}15 SP1 product installed, {slsa}{nbsp}15 SP2 and {slsa}{nbsp}15 SP3 are automatically shown in [guimenu]``Admin > Setup Wizard > Products``. 
```

2022-01-26 16:16 UTC, rjmateus commented on modules/installation-and-upgrade/pages/connect-payg.adoc
> +{productname} server uses instance credentails to connect to the RMT server and to download the packages using reposync.
```suggestion
{productname} server uses credentails collected from the instance to connect to the RMT server and to download the packages using reposync.
```

2022-01-26 16:16 UTC, rjmateus commented on modules/installation-and-upgrade/pages/connect-payg.adoc
> +Up-to date status of the {payg} instance is shown in the column Status or on the instance details page.
```suggestion
Up-to date status of the {payg} instance credentials collect is shown in the column Status or on the instance details page.
```

2022-01-26 16:16 UTC, rjmateus commented on modules/installation-and-upgrade/pages/connect-payg.adoc
> +When the instance is not reachable, the reposync will fail.
```suggestion
When the instance is not reachable, the credential update process will fail.
```

2022-01-26 16:16 UTC, rjmateus commented on modules/installation-and-upgrade/pages/connect-payg.adoc
> +{payg} instance remains connected to {productname} server unless it is explicitly deleted.
```suggestion
{payg} instance remains connected to {productname} server unless ssh connection data is explicitly deleted.
```

2022-01-26 16:16 UTC, rjmateus commented on modules/installation-and-upgrade/pages/connect-payg.adoc
> +To delete the SSH connection datato the instance, use <<proc-deleting-connection-data-to-instance>>.
```suggestion
To delete the SSH connection data to the instance, use <<proc-deleting-connection-data-to-instance>>. 
```

2022-01-26 16:16 UTC, rjmateus commented on modules/installation-and-upgrade/pages/connect-payg.adoc
> +    How long the credentials remain available depends on the cloud provider.
```suggestion
    How long the credentials remain valid depends on the cloud provider.
```

2022-01-26 18:23 UTC, jcayouette commented
Do not merge please. ATM This feature should not be released with Uyuni content, only for manager-4.3.

2022-01-26 18:40 UTC, rjmateus commented
The feature will be merged to uyuni after branch get unlocked. It will not be part of the on-going release.
It will also be part of manager 4.3 and manager 4.2.
Manager 4.2 documentation should be merged until this Friday when the branch freeze for the next Maintenance Update will happen.

2022-01-27 13:31 UTC, keichwa approved these changes

2022-01-27 13:31 UTC, keichwa commented on modules/installation-and-upgrade/pages/connect-payg.adoc
> +If the invalid data are entered at any point, the newly created instance is shown in [guimenu]``Admin > Setup Wizard > {payg}``, with column i[guimenu]``Status`` displaying error message.
```suggestion
If the invalid data are entered at any point, the newly created instance is shown in [guimenu]``Admin > Setup Wizard > {payg}``, with column [guimenu]``Status`` displaying error message.
```

2022-01-27 13:31 UTC, keichwa commented on modules/installation-and-upgrade/pages/connect-payg.adoc
> +To monitor the syncing progress of each channel, check the log files in the [path]``/var/log/rhn/reposync`` directory on the {productname} server.
```suggestion
To monitor the syncing progress of each channel, check the log files in the [path]``/var/log/rhn/reposync`` directory on the {productname} Server.
```
We usually capitalize "Server" or "Proxy" etc. after `{productname}`.

2022-01-28 08:49 UTC, jcayouette approved these changes

2022-01-31 14:34 UTC, merged