Add Troubleshooting entry about deleted clients
uyuni-project/uyuni-docs pull request #1421
Opened 2022-02-17 09:00 UTC by nodeg

# Description

This will add a new troubleshooting entry about traditional clients and how to register them as Salt minion after deleting them.
Furthermore it fixes some whitespaces in the changelog.

# Target branches

Which documentation version does this PR apply to?

- [x] Master (Default)
- [x] Manager-4.2
- [ ] Manager-4.1
- [ ] Manager-4.0

# Links

2022-02-17 09:38 UTC, keichwa requested changes
Here is my attempt to normalize it more to our style guide.  We still must look up proper xrefs.

2022-02-17 09:38 UTC, keichwa commented on modules/installation-and-upgrade/pages/troubleshooting.adoc
> +client before registering it as Salt minion:
```suggestion
////
Salt automatically detects that you have a traditional client and does the necessary changes itself.
But if you somehow deleted the traditional client and want to register it as a Salt minion again, you have to do the following steps on the client before registering it as Salt minion:
////
```
I think we do not need the above text.  But keeping for reference for the moment, commented.

2022-02-17 09:38 UTC, keichwa commented on modules/installation-and-upgrade/pages/troubleshooting.adoc
> +This is not a valid scenario. Normally you migrate a traditional client to a Salt minion without deleting the client.
```suggestion
It is recommended to migrate a traditional client to a Salt client directly without deleting it first.
For more information about this migration procedure, see xref:xxx

If you deleted the traditional client by accident, proceed as follows:
```

2022-02-17 09:38 UTC, keichwa commented on modules/installation-and-upgrade/pages/troubleshooting.adoc
> +
```suggestion
.Procedure: Registering traditional client as a Salt client
```

2022-02-17 09:38 UTC, keichwa commented on modules/installation-and-upgrade/pages/troubleshooting.adoc
> +. Remove the following file:
```suggestion
. On the client, remove the following file:
```

2022-02-17 09:38 UTC, keichwa commented on modules/installation-and-upgrade/pages/troubleshooting.adoc
> +. Remove the following package:
```suggestion
. On the client, remove the [package]``zypp-plugin-spacewalk`` package:
```

2022-02-17 09:38 UTC, keichwa commented on modules/installation-and-upgrade/pages/troubleshooting.adoc
> +zypp-plugin-spacewalk
```suggestion
zypper rm zypp-plugin-spacewalk
```

2022-02-17 09:38 UTC, keichwa commented on modules/installation-and-upgrade/pages/troubleshooting.adoc
> ++
```suggestion
. Register the client now as a Salt client.
  For more information, see xref:xxx
```

2022-02-17 09:38 UTC, keichwa commented on .changelog
> +  as Salt minion.
```suggestion
- Documented registering a deleted traditional client as Salt client in
  the troubleshooting section of the Installation and Upgrade Guide.
```

2022-02-17 10:01 UTC, nodeg commented
Thank you for the extensive review @keichwa.  I committed your suggestions.

2022-02-17 13:43 UTC, keichwa requested changes
thanks for all your merges.  here are now my final suggestions.

2022-02-17 13:43 UTC, keichwa commented on modules/installation-and-upgrade/pages/troubleshooting.adoc
> +  For more information, see xref:xxx
```suggestion
  For more information, see xref:client-configuration:registration-methods-saltbundle.adoc[].
```

2022-02-17 13:43 UTC, keichwa commented on modules/installation-and-upgrade/pages/troubleshooting.adoc
> +For more information about this migration procedure, see xref:xxx
```suggestion
Salt detects that you have a traditional client and migrates it to the Salt contact method automatically.
```
I could find this describe elsewhere in our documentation.  Thus no xref: here.

2022-02-17 13:43 UTC, keichwa commented on modules/installation-and-upgrade/pages/troubleshooting.adoc
> +////
```suggestion
```
I think we can remove this now.

2022-02-17 13:59 UTC, nodeg commented on modules/installation-and-upgrade/pages/troubleshooting.adoc
> +////
Agreed.

2022-02-21 15:22 UTC, keichwa approved these changes
now it LGTM!

2022-02-22 13:24 UTC, keichwa commented
If you have merge right, please "squash and merge".  If not, I can do it for you!

2022-02-22 14:22 UTC, 0rnela approved these changes

2022-02-24 10:36 UTC, nodeg commented
I did a rebase because of conflicts in the changelog.

2022-02-24 10:46 UTC, merged