createrepo proposal (#1403)
uyuni-project/uyuni-docs pull request #1482
Opened 2022-03-16 07:48 UTC by keichwa

https://github.com/SUSE/spacewalk/issues/16827
https://bugzilla.suse.com/show_bug.cgi?id=1195294
* more general description; per feedback
* Update modules/administration/pages/custom-channels.adoc
Co-authored-by: Michael Calmer <mc@suse.de>

# Description

Short summary of why you created this PR

# Target branches

Which documentation version does this PR apply to?

- [ ] Master (Default)
- [x] Manager-4.2
- [ ] Manager-4.1
- [ ] Manager-4.0

# Links

Fixes #<insert issue or PR link, if any>

2022-03-16 07:49 UTC, keichwa commented on .changelog
> +  documentation improvements (bsc#1195145)
```suggestion
```

2022-03-16 08:06 UTC, keichwa commented
I hope I got it right.

2022-03-17 10:27 UTC, jcayouette approved these changes

2022-03-17 10:27 UTC, jcayouette requested changes
Looks good but I see some conflicts in the changelog.

2022-03-17 12:27 UTC, keichwa commented on .changelog
> +  about creating metadata (bsc#1195294)
```suggestion
  about creating metadata (bsc#1195294)
- In the Client Configuration Guide, mark Yomi as unsupported on SLES 11 and 12
  - Documented GPG encrypted Salt Pillars in the Salt book.
- Clarified channel label name in Registering Clients with RHUI section of the
  Client Configuration Guide (bsc#1196067)
- In Throubleshooting Synchronization chapter in the Administration Guide
  added instructions for GPG removal.
- In Client Configuration Guide, integrated SLE Micro Client documentation
  next to SUSE Linux Enterprise Client documentation and other related
  documentation improvements (bsc#1195145)
```

2022-03-17 12:28 UTC, keichwa commented on .changelog
> +  - Documented GPG encrypted Salt Pillars in the Salt book.
```suggestion
- Documented GPG encrypted Salt Pillars in the Salt book.
```

2022-03-21 15:24 UTC, merged