Workflow renamed
uyuni-project/uyuni-docs pull request #1538
Opened 2022-04-21 18:29 UTC by 0rnela

# Description

Workflow renamed to bring it higher up on the nav bar.

# Target branches

Which documentation version does this PR apply to?

- [x] Master (Default)
- [ ] Manager-4.2
- [ ] Manager-4.1
- [ ] Manager-4.0

# Links

Fixes #<insert issue or PR link, if any>

2022-04-25 06:32 UTC, keichwa approved these changes

2022-06-21 11:44 UTC, jcayouette approved these changes

2022-06-21 11:44 UTC, jcayouette requested changes
Please fix conflicts. Looks good otherwise

2022-08-09 16:30 UTC, 0rnela commented
Old.

2022-08-09 16:30 UTC, closed without merging