remove deprecated reportdb schema image
uyuni-project/uyuni-docs pull request #1543
Opened 2022-04-26 10:04 UTC by mbussolotto

# Description

Remove deprecated reportdb schema image. As soon the reportdb documentation will be created directly from the code, a link will be added here

# Target branches

Which documentation version does this PR apply to?

- [x] Master (Default)
- [ ] Manager-4.2
- [ ] Manager-4.1
- [ ] Manager-4.0

# Links

Fixes #<insert issue or PR link, if any>

2022-04-26 10:26 UTC, mcalmer requested changes

2022-04-26 10:26 UTC, mcalmer commented on modules/specialized-guides/pages/large-deployments/hub-reporting.adoc
> -image::reportdb_schema.png[]
Can we add some text where to find the documentation now?

2022-04-26 14:26 UTC, keichwa approved these changes

2022-04-26 14:26 UTC, keichwa commented on modules/specialized-guides/pages/large-deployments/hub-reporting.adoc
>  Another common additional field is `synced_date`, which represent the time when the data were exported from the main {productname} Server database.
```suggestion
Another common additional field is `synced_date`, which represents the time when the data were exported from the main {productname} Server database.
```

2022-04-27 07:33 UTC, keichwa approved these changes
If no more feedback arrives, or if nobody vetoes, I'll merge it tomorrow (or earlier if wanted).

2022-04-27 07:47 UTC, mbussolotto commented
@mackdk do you think we are able to release the online documentation soon? or is there any link/path where to find the update schema documentation before it's online?  Thanks!

2022-04-30 08:07 UTC, mcalmer approved these changes

2022-05-02 06:19 UTC, keichwa approved these changes
Thanks, sounds good.  Contents ready to be merged, IMO.

Later we (doc-squad) can normalize it a little bit more according to the documentation style guide.

2022-05-02 06:41 UTC, merged