remove "add 20.04 universe
uyuni-project/uyuni-docs pull request #1664
Opened 2022-07-19 11:21 UTC by keichwa

# Description

ubuntu 20.04 requires universe channels (per feedback by Julio)

# Target branches

Which documentation version does this PR apply to?

- [x] Master (Default)
- [ ] Manager-4.2
- [ ] Manager-4.1
- [ ] Manager-4.0

# Links

Fixes #<insert issue or PR link, if any>

2022-07-19 11:23 UTC, keichwa commented
See chapter 4.12: [uyuni_client-configuration_guide.pdf](https://github.com/uyuni-project/uyuni-docs/files/9140543/uyuni_client-configuration_guide.pdf)

2022-07-19 14:31 UTC, juliogonzalez requested changes
LGTM, only one thing that should be changed

But also: @keichwa did you verify the channel names on a real Uyuni instance, just in case? If not, please check them *before* merging.

Then add me as reviewer, and I will approve :_)

2022-07-19 14:31 UTC, juliogonzalez commented on modules/client-configuration/pages/clients-ubuntu.adoc
> +.Ubuntu Universe Channels - CLI
```suggestion
.Ubuntu 20.04 Universe Channels - CLI
```

2022-07-20 09:16 UTC, keichwa commented
@juliogonzalez thanks! I now also added the backports channel.  If wrongly, I'll remove it.

2022-07-20 09:44 UTC, jcayouette approved these changes

2022-07-20 09:44 UTC, jcayouette commented
Thanks @keichwa Looks good 👍

2022-07-20 09:48 UTC, juliogonzalez approved these changes
LGTM. Go ahead and merge :-)

2022-07-20 11:09 UTC, merged