Documented Ubuntu 22.04 LTS again
uyuni-project/uyuni-docs pull request #1670
Opened 2022-07-21 15:25 UTC by keichwa

# Description

Documented Ubuntu 22.04 LTS again (for 4.3.2.MU)

# Target branches

Which documentation version does this PR apply to?

- [ ] Master (Default)
- [x] Manager-4.3

# Links

Fixes #<insert issue or PR link, if any>

2022-08-17 11:45 UTC, keichwa commented
[suse_manager_client-configuration_guide.pdf](https://github.com/uyuni-project/uyuni-docs/files/9359047/suse_manager_client-configuration_guide.pdf)

2022-08-18 08:01 UTC, juliogonzalez requested changes
Seems there's an error rendering one of the tables. Not sure if it affects master as well.

2022-08-18 08:43 UTC, keichwa commented on modules/client-configuration/pages/supported-features-ubuntu.adoc
> +| {ubuntu}{nbsp}22.04
thanks for spotting.  master is probably also effected.
[suse_manager_client-configuration_guide.pdf](https://github.com/uyuni-project/uyuni-docs/files/9371933/suse_manager_client-configuration_guide.pdf)

2022-09-09 13:53 UTC, jcayouette approved these changes

2022-09-09 13:55 UTC, jcayouette commented
I approved but what about this rendering of the pdf table?

2022-09-14 05:41 UTC, keichwa commented
> I approved but what about this rendering of the pdf table?

According to my build, the table is now fixed. Thanks for checking!

2022-09-14 06:34 UTC, merged