backport43 - GPG snippet related changes in client files
uyuni-project/uyuni-docs pull request #1694
Opened 2022-07-28 13:41 UTC by 0rnela

# Description

Leftover change in the snippet has been identified.

# Target branches

Which documentation version does this PR apply to?

- [ ] Master (Default)
- [x] Manager-4.3
- [ ] Manager-4.2

# Links
....

2022-08-01 05:13 UTC, keichwa requested changes

2022-08-01 05:13 UTC, keichwa commented on modules/client-configuration/pages/clients-almalinux.adoc
> +It is the task of the adminstrator to decide which keys are needed and can be trusted.
```suggestion
It is the task of the administrator to decide which keys are needed and can be trusted.
```

2022-08-01 05:13 UTC, keichwa commented on modules/client-configuration/pages/clients-ubuntu-old.adoc
> +For information about registering Salt clients running {ubuntu} 20.04 and 22.04, see xref:client-configuration:clients-ubuntu.adoc[].
seems to be unrelated to the GPG changes.

2022-08-01 05:13 UTC, keichwa commented on modules/client-configuration/pages/clients-ubuntu.adoc
> += Registering {ubuntu} 20.04 and 22.04 Clients
This and the following changes seem to be unrelated to the GPG changes.

2022-08-01 05:13 UTC, keichwa commented on modules/client-configuration/pages/snippets/trust_gpg.adoc
> +Because a software channel cannot be used when the GPG key is not trusted, the decision of assigning a channel to a client depends on the decision of trusting the key.
I think the old version is better.

2022-08-01 05:13 UTC, keichwa commented on modules/client-configuration/pages/clients-almalinux.adoc
> +Because a software channel cannot be used when the GPG key is not trusted, the decision of assigning a channel to a client depends on the decision of trusting the key.
I proposed an accepted phrase in the old or existing `modules/client-configuration/pages/snippets/trust_gpg.adoc` file.  I'd appreciate if we could use this wording.  Also in `master` we probably should use this wording:
> It is the task of the administrator to decide which keys are needed and can be trusted.
> A software channel cannot be assigned to a client when the GPG key is not trusted.

2022-08-04 13:46 UTC, jcayouette approved these changes

2022-08-09 11:22 UTC, closed without merging