fix typo
uyuni-project/uyuni-docs pull request #1711
Opened 2022-08-10 08:55 UTC by keichwa

# Description
https://github.com/uyuni-project/uyuni-docs/issues/1710
https://github.com/SUSE/spacewalk/issues/18570

# Target branches

Which documentation version does this PR apply to?

- [ ] Master (Default)
- [ ] Manager-4.3
- [ ] Manager-4.2

# Links

Fixes #<insert issue or PR link, if any>

2022-08-10 09:02 UTC, keichwa commented on modules/administration/pages/openscap.adoc
> +For Non-{suse} OSs, note that the included profiles are community supplied and not officially supported by {suse}.
```suggestion
For Non-{suse} operating systems the included profiles are community supplied.
They are not officially supported by {suse}.
```
drive-by wording change

2022-08-10 09:17 UTC, 0rnela approved these changes

2022-08-10 09:19 UTC, jcayouette requested changes
Your content looks fine, but I see an unused file in Reference guide? Any idea why this is not being used atm?

2022-08-11 09:08 UTC, keichwa commented
The unused file is unrelated to this PR.  Thus pushing now.

2022-08-11 09:08 UTC, merged