Adjust the containerized proxy to match the new installation process
uyuni-project/uyuni-docs pull request #1750
Opened 2022-09-09 13:45 UTC by cbosdo

# Description

Since 2022.08 and 4.3.1, the containerized proxy installation and configuration has slightly changed. This PR updates the doc according to the new standard.

# Target branches

Which documentation version does this PR apply to?

- [X] Master (Default)
- [X] Manager-4.3
- [ ] Manager-4.2

# Links

Fixes #<insert issue or PR link, if any>

2022-09-09 13:50 UTC, jcayouette approved these changes

2022-09-09 15:31 UTC, keichwa requested changes
Some cosmetic changes.

2022-09-09 15:31 UTC, keichwa commented on modules/installation-and-upgrade/pages/proxy-container-installation.adoc
> +To override the default volume settings, create the volumes prior to the first start of the pod using the [literal]``podman volume create`` command
```suggestion
To override the default volume settings, create the volumes prior to the first start of the pod using the [literal]``podman volume create`` command.
```

2022-09-09 15:31 UTC, keichwa commented on modules/installation-and-upgrade/pages/proxy-container-installation.adoc
> +In this file it is possible to modify the tag to use for the container images
```suggestion
In this file it is possible to modify the tag to use for the container images:
```

2022-09-09 15:31 UTC, keichwa commented on modules/installation-and-upgrade/pages/proxy-container-installation.adoc
> +- [literal]`TAG`=[path]`latest`
```suggestion
- [literal]``TAG``=[path]``latest``
```

2022-09-12 06:29 UTC, cbosdo commented
@keichwa I just merged all your suggestions

2022-09-12 10:24 UTC, keichwa approved these changes
Thank you, Cedric!  If you don't veto, I'll merge it in the afternoon.

2022-09-12 12:15 UTC, merged