Added secure mail communication settings in Administration Guide
uyuni-project/uyuni-docs pull request #1757
Opened 2022-09-13 13:40 UTC by keichwa

# Description

support for smtp port, auth and ssl/tls config in rhn.cfg
https://github.com/SUSE/spacewalk/issues/18187

# Target branches

Which documentation version does this PR apply to?

- [x] Master (Default)
- [ ] Manager-4.3
- [ ] Manager-4.2

# Links

Fixes #<insert issue or PR link, if any>

2022-09-13 13:45 UTC, keichwa commented
Just basic info.  Do you think we must provide background info?  If yes, which one?  @wombelix , can you please also review this PR?

@0rnela is there a better place where we should add such info?

2022-09-13 14:40 UTC, 0rnela requested changes

2022-09-13 14:40 UTC, 0rnela commented on modules/administration/pages/tshoot-mail.adoc
> +[[troubleshooting-notifications]]
```suggestion
[[troubleshooting-mail- configuration]]
```

2022-09-14 14:10 UTC, 0rnela approved these changes

2022-09-20 14:39 UTC, merged