Update clients ubuntu eins (#1791)
uyuni-project/uyuni-docs pull request #1811
Opened 2022-10-11 07:39 UTC by keichwa

# Description

* fix ubuntu base channel pool-amd64
Co-authored-by: Galaxy CI <galaxy-ci@suse.de>
Co-authored-by: Karl Eichwalder <ke@suse.de>

# Target branches

Which documentation version does this PR apply to?

- [ ] Master (Default)
- [ ] Manager-4.3
- [x] Manager-4.2

# Links

Fixes #<insert issue or PR link, if any>

2022-10-11 12:23 UTC, juliogonzalez requested changes

2022-10-11 12:23 UTC, juliogonzalez commented on modules/client-configuration/pages/clients-ubuntu.adoc
> +<<<<<<< HEAD
Please create a render of this documentation. I am quite sure this is wrong, as well as other lines later.

Seems you have an unfixed conflict.

2022-10-12 10:58 UTC, keichwa commented
@juliogonzalez thanks for spotting!  I fixed this issue, but now I see that we need more changes to do it properly.  Updating feature tables and more suma related are required...  Because I'm not familiar with this client system it would probably take some time.  Do we have to add version 22.04 to the SUMA 4.2 documentation?

2022-10-20 11:17 UTC, 0rnela approved these changes

2022-10-25 11:59 UTC, keichwa commented
per feedback: backport not needed;it was an uyuni-only issue.

2022-10-25 11:59 UTC, closed without merging