Ccg rhel9rhel #18472 keichwa (#1789)
uyuni-project/uyuni-docs pull request #1926
Opened 2022-11-30 12:43 UTC by keichwa

# Description

* add rhel 9

# Target branches

Which documentation version does this PR apply to?

- [ ] Master (Default)
- [x] Manager-4.3
- [ ] Manager-4.2

# Links

Fixes #<insert issue or PR link, if any>

2022-11-30 12:51 UTC, keichwa commented
[suse_manager_client-configuration_guide.pdf](https://github.com/uyuni-project/uyuni-docs/files/10123269/suse_manager_client-configuration_guide.pdf)

2022-11-30 15:48 UTC, srbarrios commented on modules/client-configuration/pages/clients-rh-cdn.adoc
> +| {redhat} 9 | RHEL 9 Base
I'm not fully sure if that's the correct name, I think we included Liberty word on it.

2022-11-30 15:49 UTC, srbarrios commented on modules/client-configuration/pages/clients-rh-cdn.adoc
> +| res9-suse-manager-tools-x86_64
I would say this was changed, and now instead of res9 we use el9.
Please check with @juliogonzalez

2022-11-30 15:49 UTC, srbarrios commented on modules/client-configuration/pages/clients-rh-cdn.adoc
> +| {redhat} 9 | RHEL 9 Base | rhel9-pool-x86_64
Base product name, I'm not sure if it's correct.

2022-11-30 16:46 UTC, lucidd commented
just a comment on any naming related questions i don't think there should be any difference to the uyuni pr so use that as reference.

2022-11-30 17:54 UTC, keichwa commented on modules/client-configuration/pages/clients-rh-cdn.adoc
> +Traditional clients are available on {rhel}{nbsp}6 and 7 only.
AFAIK, we removed rhel 6 from the table of supported products.   Removing all references to a no longer supported client system is a different thing (imo).  I'll remove it if someone wants me to do it.

2022-12-01 08:17 UTC, keichwa commented
Michael, Can, or Kevin, can you please help with reviewing?  If changes are required, I'd prefer (literal) suggestions that you can enter with Ctrl-g linewise.  I know you know this but some things you cannot say often enough ;)

2022-12-01 10:16 UTC, mcalmer requested changes

2022-12-01 10:16 UTC, mcalmer commented on modules/client-configuration/pages/clients-rh-cdn.adoc
> +| rhel9-pool-x86_64
```suggestion
| el9-pool-x86_64
```

2022-12-01 10:16 UTC, mcalmer commented on modules/client-configuration/pages/clients-rh-cdn.adoc
> +| res9-suse-manager-tools-x86_64
```suggestion
| el9-manager-tools-pool-x86_64, el9-manager-tools-updates-x86_64
```

2022-12-01 10:16 UTC, mcalmer commented on modules/client-configuration/pages/clients-rh-cdn.adoc
> +| {redhat} 9 | RHEL and Liberty 9 Base | rhel9-pool-x86_64
```suggestion
| {redhat} 9 | RHEL and Liberty 9 Base | el9-pool-x86_64
```

2022-12-01 10:16 UTC, mcalmer commented on modules/client-configuration/pages/clients-rh-rhui.adoc
> +| res9-suse-manager-tools-x86_64
```suggestion
| {redhat} 9
| el9-pool-x86_64
| -
| el9-manager-tools-pool-x86_64, el9-manager-tools-updates-x86_64
```

2022-12-01 10:16 UTC, mcalmer commented on modules/client-configuration/pages/clients-rh-rhui.adoc
> +| {redhat} 9 | RHEL and Liberty 9 Base          | rhel9-pool-x86_64
```suggestion
| {redhat} 9 | RHEL and Liberty 9 Base          | el9-pool-x86_64
```

2022-12-01 10:16 UTC, mcalmer commented on modules/client-configuration/pages/clients-sleses.adoc
Not sure if this doc update should already include SLL9. AFAIK we moved the support for it by 1 release.

2022-12-01 10:36 UTC, keichwa commented on modules/client-configuration/pages/clients-sleses.adoc
I'd like to discuss SLL9 here: https://github.com/uyuni-project/uyuni-docs/pull/1899
mc, thanks for your review and patches.  I'll now add you to #1899 , too.  There we have related open questions.

2022-12-01 11:48 UTC, 0rnela commented on modules/client-configuration/pages/clients-rh-cdn.adoc
> +Traditional clients are available on {rhel}{nbsp}6 and 7 only.
I'm removing them as I come across them.

2022-12-01 11:48 UTC, mcalmer approved these changes
LGTM

2022-12-01 12:26 UTC, srbarrios commented on modules/client-configuration/pages/clients-rh-cdn.adoc
> +Traditional clients are available on {rhel}{nbsp}6 and 7 only.
Thank you Ornela. I would say removing the references of RHEL6 can go to a different PR.
But that's definitely something to address.

2022-12-01 12:26 UTC, merged

2022-12-01 12:27 UTC, srbarrios approved these changes
LGTM

2022-12-01 12:31 UTC, srbarrios commented
@keichwa please keepn in mind you will also need to port this to the branch of the MU for 4.3.3

2022-12-01 12:31 UTC, juliogonzalez commented
This PR does not go against the branch for the MU, so I have no idea if Joseph will be able to prepare the right package and SRs.

@keichwa please sync with Joseph and clarify it.

@deneb-alpha, ping for your awareness.

2022-12-01 13:11 UTC, keichwa commented
Oscar Barrios ***@***.***> writes:

> @keichwa please keep in mind you will also need to port this to the
> branch of the MU for 4.3.3

Julio González Gil ***@***.***> writes:

> This PR does not go against the branch for the MU, so I have no idea
> if Joseph will be able to prepare the right package and SRs.
>
> @keichwa please sync with Joseph and clarify it.

Thanks for the reminder. I'll prepare a separate PR.

-- 
Karl Eichwalder                       SUSE Software Solutions Germany GmbH
                                      Frankenstraße 146, D-90461 Nürnberg
Geschäftsführer: Ivo Totev, Andrew Myers, Andrew McDonald, Boudien Moerman
(HRB 36809, AG Nürnberg)

2022-12-01 15:33 UTC, keichwa commented
now we also have https://github.com/uyuni-project/uyuni-docs/pull/1932

-- 
Karl Eichwalder                       SUSE Software Solutions Germany GmbH
                                      Frankenstraße 146, D-90461 Nürnberg
Geschäftsführer: Ivo Totev, Andrew Myers, Andrew McDonald, Boudien Moerman
(HRB 36809, AG Nürnberg)