Capping single-server support to 10 000 minions
uyuni-project/uyuni-docs pull request #1939
Opened 2022-12-05 12:35 UTC by 0rnela

# Description

From the original issue: "Some customers are still using suse manager deployment with just one server to manage a huge amount of minions (18k)."

This PR explicitly states that the maximum number of clients supported per single server is 10 000.

Content added to:
1. HW Requirements page in the form of warning and link to Large Deployments.
2. Existing Large deployments file changed to give more explicit guidelines (i.e. "you might find it easier" was replaced by "you need to use multiple {productname} Servers in a hub").

# Target branches

Which documentation version does this PR apply to?

- [x] Master (Default)
- [x] Manager-4.3
- [x] Manager-4.2

# Links

Fixes https://github.com/SUSE/spacewalk/issues/19491

2022-12-05 12:38 UTC, rjmateus approved these changes
Looks good to me

2022-12-05 12:44 UTC, aaannz reviewed
Two typos and hope @admd is aware of this as it is in quite strong language. Appears like hard limit, which is ok I just imagine some customers may start panicking after reading it.

2022-12-05 12:44 UTC, aaannz commented on modules/installation-and-upgrade/pages/hardware-requirements.adoc
> +Reistering higher than maximum number is not supported by {suse}.
```suggestion
Registering higher than maximum number is not supported by {suse}.
```

2022-12-05 12:44 UTC, aaannz commented on modules/specialized-guides/pages/large-deployments/multi-server.adoc
> +Reistering higher than maximum number on a single {productname} Server is not supported by {suse}.
```suggestion
Registering higher than maximum number on a single {productname} Server is not supported by {suse}.
```

2022-12-05 12:47 UTC, rjmateus commented
That is a good point @aaannz 
Maybe something like "{suse} may not support systems with a registration number a higher than maximum number on a single {productname} Server."

What do you guys think?

2022-12-05 12:51 UTC, 0rnela commented
Sounds good @rjmateus and @aaannz, I'll amend.

My understanding was that we indeed need to prevent the customers from overstretching the servers, and that we should express it more directly.

I'll make the new changes.

2022-12-05 13:45 UTC, 0rnela commented
@rjmateus @aaannz -- after discussing with @keichwa we take the approach that we should avoid "may, may be" phrasing as it does not give customers clear guidelines to follow and leaves things open to interpretation.

The intention of this PR / original issue was to cap the number of clients per single server, and these changes address that.

However, to avoid the risk of panic of any kind, the following sentence was added:
"Customers can ask support for advice or exception depending on their own workload."

I hope this resolves the issues.

Please let me know otherwise.

2022-12-05 14:26 UTC, 0rnela commented
> 👍🏾

Thank you @aaannz .

2022-12-05 16:20 UTC, admd requested changes
I agree with the reservations mentioned above. There are quite a few customers out there who are running more than 10k with a single SUMA and number of proxies. Adding such paragraph would definitely create panic as it suggests they are not supported anymore. 

We need better wording and going more along the advise rather black & white supported/not supported.

2022-12-05 16:20 UTC, admd commented on modules/installation-and-upgrade/pages/hardware-requirements.adoc
> +Maximum number of clients which can be managed by a single {productname} server is 10 000.
I am not sure about the wording here as was pointed by other colleagues. We should be going for like "It is advisable or strongly recommended to move to Hub setup ad involve consultancy once you have more than 10k number of minions" , not exactly what I mentioned but along those lines.

2022-12-06 13:22 UTC, 0rnela commented
A lot of additional files got pulled in during conflict resolutions. Creating new, clean PR.

2022-12-06 13:22 UTC, closed without merging