Added missing PAYG page to Reference Guide
uyuni-project/uyuni-docs pull request #1948
Opened 2022-12-08 16:55 UTC by 0rnela

# Description

There was no PAYG page mentioned in the Reference Guide (https://bugzilla.suse.com/show_bug.cgi?id=1205217)

# Target branches

Which documentation version does this PR apply to?

- [x] Master (Default)
- [x] Manager-4.3
- [x] Manager-4.2

# Links

Fixes https://github.com/SUSE/spacewalk/issues/19492.

2022-12-13 09:39 UTC, keichwa requested changes

2022-12-13 09:39 UTC, keichwa commented on modules/reference/pages/admin/payg.adoc
> +To add new instance, click [button]``Add {payg}``.
```suggestion
To add new instance, click btn:[Add {payg}].
```
I do not know whether your variant would work, too.

2022-12-13 10:05 UTC, keichwa approved these changes

2022-12-15 09:22 UTC, jcayouette commented on modules/reference/pages/admin/payg.adoc
> +Every instance shows its description and connection data.
Each instance...

2022-12-19 14:06 UTC, 0rnela commented on modules/reference/pages/admin/payg.adoc
> +Every instance shows its description and connection data.
```suggestion
A description and connection parameters are displayed for each instance
```

2022-12-19 14:06 UTC, merged