Add Grafana configuration information
uyuni-project/uyuni-docs pull request #1949
Opened 2022-12-09 08:48 UTC by witekest

# Description

Add steps for manual Grafana configuration

# Target branches

Which documentation version does this PR apply to?

- [ ] Master (Default)
- [ ] Manager-4.3
- [ ] Manager-4.2

# Links

Fixes SUSE/spacewalk#19714

2022-12-09 08:50 UTC, witekest commented
I'm not sure if the screenshot is added in a right way. When building locally it was not rendered.
Apart from that it also breaks the numbering of the list.

2022-12-12 11:46 UTC, 0rnela requested changes

2022-12-12 11:46 UTC, 0rnela commented on modules/administration/pages/monitoring.adoc
> +image::grafana_sidemenu_datasource.png[scaledwidth=40%]
```suggestion
+
image::grafana_sidemenu_datasource.png[scaledwidth=40%]
```

2022-12-12 11:46 UTC, 0rnela commented on modules/administration/pages/monitoring.adoc
>  image::monitoring_grafana_example.png[scaledwidth=80%]
```suggestion
+
image::monitoring_grafana_example.png[scaledwidth=80%]
```

2022-12-12 11:48 UTC, 0rnela requested changes

2022-12-12 11:48 UTC, 0rnela commented on modules/administration/pages/monitoring.adoc
> +. Click btn:[Log in]. If login is successful, then you will see a prompt to change the password.
```suggestion
. Click btn:[Log in]. 
    If login is successful, then you will see a prompt to change the password.
```

2022-12-12 11:48 UTC, 0rnela commented on modules/administration/pages/monitoring.adoc
> +
```suggestion
```

2022-12-12 11:48 UTC, 0rnela commented on modules/administration/pages/monitoring.adoc
```suggestion
```

2022-12-13 09:36 UTC, keichwa approved these changes

2022-12-13 09:44 UTC, 0rnela approved these changes

2022-12-13 09:55 UTC, merged