Cobbler support statement
uyuni-project/uyuni-docs pull request #1995
Opened 2023-01-10 17:38 UTC by keichwa

# Description

https://bugzilla.suse.com/show_bug.cgi?id=1206963
https://github.com/SUSE/spacewalk/issues/20083

# Target branches

Which documentation version does this PR apply to?

- [x] Master (Default)
- [ ] Manager-4.3
- [ ] Manager-4.2

# Links

Fixes #<insert issue or PR link, if any>

2023-01-10 17:46 UTC, SchoolGuy approved these changes
LGTM

2023-01-11 10:53 UTC, nodeg requested changes
Cobbler is wirtten with a capital C and also to be consistent with the line above.

2023-01-11 10:53 UTC, nodeg commented on modules/client-configuration/pages/autoinst-intro.adoc
> +For more information about cobbler, see https://cobbler.readthedocs.io.
```suggestion
For more information about Cobbler, see https://cobbler.readthedocs.io.
```

2023-01-11 11:19 UTC, keichwa commented
> Cobbler is wirtten with a capital C and also to be consistent with the line above.

Thanks, good point.  I should probably check the complete file or even all the books in a separate PR.

2023-01-11 12:10 UTC, nodeg approved these changes

2023-01-11 12:30 UTC, merged