[WIP] How to configure external database during server setup
uyuni-project/uyuni-docs pull request #2004
Opened 2023-01-13 03:31 UTC by maximenoel8

# Description

Describe in server setup section how to configure an external database using mgr-setup

# Target branches

Which documentation version does this PR apply to?

- [x] Master (Default)
- [x] Manager-4.3

2023-01-16 12:55 UTC, mcalmer commented
removed "4.3" as we only merged it in master

2023-01-17 04:38 UTC, maximenoel8 commented
How can I add reviewer to this PR ?  I may not have the rights.

2023-01-19 11:19 UTC, keichwa commented
I forgot to mention that we'd appreciate if you'd add a changelog entry at the top of the `.changelog` in the toplevel directory of this repo.  Thanks for your help!

2023-01-20 09:44 UTC, keichwa requested changes

2023-01-20 09:48 UTC, keichwa commented
@maximenoel8 something went wrong with my review submission yesterday.  Now you should see them. If possible, please check them and commit those that make sense to you.  It's mostly just cosmetic stuff.  Thanks!

2023-01-23 05:54 UTC, maximenoel8 commented
Thanks for the review. I follow your remarks. Just to be sure, is it understandable that all the section I describe need to be in setup_env.sh ?

2023-01-23 09:50 UTC, keichwa requested changes

2023-01-23 09:50 UTC, keichwa commented on modules/installation-and-upgrade/pages/server-setup.adoc
> +First create a [path]``setup_env.sh`` file in the [path]``/root`` directory defining the server setup like this:
```suggestion
. First create a [path]``setup_env.sh`` file in the [path]``/root`` directory defining the server setup.
  The details are explained in the following steps.
```

2023-01-23 09:50 UTC, keichwa commented on modules/installation-and-upgrade/pages/server-setup.adoc
> +. Here you define your certificate information and password.
```suggestion
. Set the variables defining your certificate information and password.
```

2023-01-23 09:50 UTC, keichwa commented on modules/installation-and-upgrade/pages/server-setup.adoc
> +The information are the same as <<proc-quickstart-certificate-information-yast>>.
```suggestion
The information is the same as explained at <<proc-quickstart-certificate-information-yast>>.
```

2023-01-23 09:50 UTC, keichwa commented on modules/installation-and-upgrade/pages/server-setup.adoc
> +. Define the specific configuration for the external database.
```suggestion
. Set the variables defining the specific configuration for the external database.
```

2023-01-23 09:53 UTC, keichwa commented
> Thanks for the review. I follow your remarks. Just to be sure, is it understandable that all the section I describe need to be in setup_env.sh ?

Thanks for following up!  I'm now proposing additional tweaks for clarity.  I hope I got it right.  If yes, please commit the suggestions.

2023-01-23 10:30 UTC, jcayouette approved these changes
Other than Karl's requested changes looks great!

2023-01-24 09:06 UTC, keichwa commented
> I committed your suggestions. Fill free to merge the documentation once it's accepted on your side !

Thanks for all your help!

2023-01-24 09:07 UTC, keichwa approved these changes

2023-01-24 09:08 UTC, merged