Retail documentation rework including containerized retail
uyuni-project/uyuni-docs pull request #2090
Opened 2023-02-21 11:35 UTC by aaannz

# Description

Port of https://github.com/uyuni-project/uyuni-docs/pull/1574

Rework retail documentation to cover different configuration ways by including example configurations.

Include instructions how to configure retail using containerized proxy in the examples.

# Target branches

Which documentation version does this PR apply to?

- [ ] Master (Default)
- [X] Manager-4.3
- [ ] Manager-4.2

# Links

Fixes https://github.com/SUSE/spacewalk/issues/19844

2023-02-22 09:10 UTC, keichwa requested changes
I started with the review, here some typo fixes.  I'll continue later (or next week).

2023-02-22 09:10 UTC, keichwa commented on modules/retail/pages/containerized-saltboot.adoc
> +* one or more {productname} build host
```suggestion
* one or more {productname} build hosts
```

2023-02-22 09:10 UTC, keichwa commented on modules/retail/pages/containerized-saltboot.adoc
> +All [systemitem]``saltboot`` deployed machines though containerized proxy will automatically became members of its [systemitem]``Saltboot group``.
```suggestion
All [systemitem]``saltboot`` deployed machines though containerized proxy will automatically become members of its [systemitem]``Saltboot group``.
```

2023-02-22 09:36 UTC, aaannz commented
These are cherry-picked commits directly from https://github.com/uyuni-project/uyuni-docs/pull/1574

2023-02-23 10:57 UTC, keichwa approved these changes
Thanks for pointing out!  In general it LGTM!

2023-02-24 10:28 UTC, jcayouette approved these changes

2023-02-24 10:28 UTC, merged