Backport43 julio microos #20162 keichwa
uyuni-project/uyuni-docs pull request #2123
Opened 2023-03-13 12:02 UTC by keichwa

# Description

See https://github.com/SUSE/spacewalk/issues/20162 and https://github.com/uyuni-project/uyuni-docs/pull/2088

# Target branches

Which documentation version does this PR apply to?

- [ ] Master (Default)
- [x] Manager-4.3
- [ ] Manager-4.2

# Links

Fixes #<insert issue or PR link, if any>

2023-03-13 13:41 UTC, juliogonzalez requested changes
The idea is to backport only the removal of MicroOS.

Later, when 4.3 gets Leap Micro support, you can backport the rest, without ifdefs

2023-03-14 06:43 UTC, keichwa reviewed
then I probably must start over again.

2023-03-14 06:43 UTC, keichwa commented on modules/administration/pages/actions.adoc
> +For more information, see xref:client-configuration:clients-slemicro.adoc[] and xref:client-configuration:clients-opensuseleapmicro.adoc[].
```suggestion
For more information, see xref:client-configuration:clients-slemicro.adoc[] and xref:client-configuration:clients-microos.adoc[].
```

2023-03-14 06:43 UTC, keichwa commented on modules/administration/pages/actions.adoc
> +For more information, see xref:client-configuration:clients-slemicro.adoc[] and xref:client-configuration:clients-opensuseleapmicro.adoc[].
```suggestion
For more information, see xref:client-configuration:clients-slemicro.adoc[] and xref:client-configuration:clients-microos.adoc[].
```

2023-03-14 06:43 UTC, keichwa commented on modules/client-configuration/nav-client-configuration-guide.adoc
> +endif::[]
```suggestion
```

2023-03-14 06:43 UTC, keichwa commented on modules/client-configuration/nav-client-configuration-guide.adoc
> +// openSUSE Leap Micro not available at SUSE Manager for now
```suggestion
```

2023-03-14 06:43 UTC, keichwa commented on modules/client-configuration/nav-client-configuration-guide.adoc
> +**** xref:clients-opensuseleapmicro.adoc[openSUSE Leap Micro Clients]
```suggestion
**** xref:clients-microos.adoc[openSUSE MicroOS]
```

2023-03-14 09:12 UTC, keichwa commented
Yes, good idea.  This is the new PR: https://github.com/uyuni-project/uyuni-docs/pull/2130

2023-03-14 09:12 UTC, closed without merging