Ccg micro reboot #2003 keichwa
uyuni-project/uyuni-docs pull request #2234
Opened 2023-05-16 09:13 UTC by keichwa

# Description

https://github.com/SUSE/spacewalk/issues/20276
#2003 

# Target branches

Which documentation version does this PR apply to?

- [x] Master (Default)
- [ ] Manager-4.3
- [ ] Manager-4.2

# Links

Fixes #<insert issue or PR link, if any>

2023-05-23 12:42 UTC, 0rnela approved these changes

2023-05-23 12:42 UTC, 0rnela commented
@keichwa -- approved. Does it need backporting to 4.3?

2023-05-24 05:42 UTC, keichwa commented
> @keichwa -- approved. Does it need backporting to 4.3?

Welder didn't request it.  In this regard, 4.3 isn't wrong.  This PR is a clarification or enhancement. Thus I'd avoid a backport.  But I could do it if you think it's important.

2023-05-24 10:05 UTC, jcayouette requested changes

2023-05-24 10:05 UTC, jcayouette commented on modules/client-configuration/pages/clients-slemicro.adoc
> +When bootstraping a transactional system on {productname}, [systemitem]``systemd`` will be configured as the reboot method ([literal]``REBOOT_METHOD``), if the system is in its default configuration.
bootstrapping

2023-05-25 08:37 UTC, keichwa commented
> I believe it is necessary to backport it to 4.3. I apologize for not making that clear.

Thanks, noted!

2023-05-25 08:38 UTC, merged