Iau proxy container normalization #20666 keichwa
uyuni-project/uyuni-docs pull request #2352
Opened 2023-07-06 09:59 UTC by keichwa

# Description

Normalization according to https://github.com/SUSE/spacewalk/issues/20666

# Target branches

Which documentation version does this PR apply to?

- [x] Master (Default)
- [ ] Manager-4.3
- [ ] Manager-4.2

# Links

Fixes #<insert issue or PR link, if any>

2023-07-06 11:18 UTC, cbosdo approved these changes

2023-07-10 11:04 UTC, 0rnela requested changes

2023-07-10 11:04 UTC, 0rnela commented on modules/installation-and-upgrade/pages/proxy-container-installation.adoc
> +To ensure that the domain name of the {productname} Server can be resolved by its clients.
```suggestion
To ensure that domain name of the {productname} Server can be resolved by its clients.
```

2023-07-10 11:04 UTC, 0rnela commented on modules/installation-and-upgrade/pages/proxy-container-installation.adoc
>  The needed volume are named:
```suggestion
The volumes are named:
```

2023-07-10 11:25 UTC, 0rnela requested changes

2023-07-10 11:25 UTC, 0rnela commented on modules/installation-and-upgrade/pages/proxy-container-installation.adoc
>  In the [path]``/etc/sysconfig/uyuni-proxy-systemd-services.config`` file it is possible to add custom arguments passed to podman container pod:
```suggestion
It is possible to add custom arguments passed to podman container pod to [path]``/etc/sysconfig/uyuni-proxy-systemd-services.config`` file :
```

2023-07-10 11:25 UTC, 0rnela commented on modules/installation-and-upgrade/pages/proxy-container-installation.adoc
>  In this file it is possible to modify the tag to use for the container images:
```suggestion
In this file it is possible to modify tag to use for container images:
```

2023-07-10 11:25 UTC, 0rnela commented on modules/installation-and-upgrade/pages/proxy-container-installation.adoc
> +The [literal]``uyuni-proxy`` CLI bundled with the package, has an [command]``update image`` command  with the following parameters:
```suggestion
The [literal]``uyuni-proxy`` CLI bundled with the package, runs [command]``update image`` command  with the following parameters:
```

2023-07-10 11:25 UTC, 0rnela commented on modules/installation-and-upgrade/pages/proxy-container-installation.adoc
>  It would adjust a configuration file for the httpd service, taking [path]``registry.opensuse.org/uyuni`` as the registry and [literal]``0.1.0`` as the version tag and then restart it.
```suggestion
It adjusts the configuration file for the httpd service, where [path]``registry.opensuse.org/uyuni`` is the registry and [literal]``0.1.0`` is the version tag, before restarting it.
```

2023-07-10 11:25 UTC, 0rnela commented on modules/installation-and-upgrade/pages/proxy-container-installation.adoc
>  For more information, see the [literal]``uyuni-proxy --help``.
```suggestion
For more information, see [literal]``uyuni-proxy --help``.
```

2023-07-11 02:29 UTC, keichwa commented
thanks for all your suggestions, Ornela! applied.

2023-07-11 08:52 UTC, 0rnela requested changes

2023-07-11 08:52 UTC, 0rnela commented on modules/installation-and-upgrade/pages/proxy-container-installation.adoc
>  Connecting the container host as a traditional client will not work because required packages will not be available.
```suggestion
Connecting container host as a traditional client will not work because required packages will not be available.
```

2023-07-11 08:52 UTC, 0rnela commented on modules/installation-and-upgrade/pages/proxy-container-installation.adoc
>  To override the default volume settings, create the volumes prior to the first start of the pod using the [literal]``podman volume create`` command.
```suggestion
To override default volume settings, create the volumes prior to the first start of the pod using the  [command]``podman volume create`` command.
```

2023-07-11 08:54 UTC, 0rnela requested changes

2023-07-11 08:54 UTC, 0rnela commented on modules/installation-and-upgrade/pages/proxy-container-installation.adoc
>  This command would reset the configuration of the [literal]``httpd`` service to the global defaults and then restart it.
```suggestion
This command first resets the configuration of the [literal]``httpd`` service to the global defaults and then restarts it.
```

2023-07-17 11:19 UTC, merged