Uyuni only - Fixed support matrix for AlmaLinux and Rocky Linux
uyuni-project/uyuni-docs pull request #2404
Opened 2023-08-10 19:17 UTC by 0rnela

### Only approve after https://github.com/uyuni-project/uyuni-docs/pull/2403. Approval by @juliogonzalez required.

# Description

Fixed missing info and errors in the list of supported architectures.

# Target branches

Which documentation version does this PR apply to?

- [x] Master (Default)
- [x] Manager-4.3
- [ ] Manager-4.2

# Links

Fixes https://github.com/SUSE/spacewalk/issues/22170

2023-08-16 09:11 UTC, jcayouette approved these changes

2023-08-21 09:07 UTC, juliogonzalez requested changes
I am not sure why this PR is needed at all.

Also seems https://github.com/uyuni-project/uyuni-docs/pull/2403 was not right, you maybe need to rollback that PR.

The issue you are mentioned, https://github.com/SUSE/spacewalk/issues/22170 doesn't apply in all cases for SUSE Manager and Uyuni.

EoL products are to be removed from both SUSE Manager and Uyuni. Architectures, not always.

2023-08-21 09:07 UTC, juliogonzalez commented on modules/client-configuration/pages/supported-features.adoc
> +| {x86_64}, {aarch64}
Not right. For Alma9 we support  x86_64, aarch64, ppc64le, s390x, at least on Uyuni :-)

2023-08-21 09:07 UTC, juliogonzalez commented on modules/client-configuration/pages/supported-features.adoc
> +| {x86_64}, {aarch64}
Not right. For Rocky9 we support  x86_64, aarch64, ppc64le, s390x, at least on Uyuni :-)

2023-08-21 09:07 UTC, juliogonzalez commented on modules/installation-and-upgrade/pages/client-requirements.adoc
> +| {x86_64}, {aarch64}
Same

2023-08-21 09:07 UTC, juliogonzalez commented on modules/installation-and-upgrade/pages/client-requirements.adoc
> +| {x86_64}, {aarch64}
Same

2023-08-21 09:07 UTC, juliogonzalez commented on modules/installation-and-upgrade/pages/client-requirements.adoc
> +| {x86_64}, {aarch64}
Same

2023-08-24 09:35 UTC, juliogonzalez commented
> I am not sure why this PR is needed at all.

This is still valid, Uyuni supports all four architectures.

> Also seems #2403 was not right, you maybe need to rollback that PR.

I was wrong about this, I didn't notice you changed only the SUSE Manager part on #2403 as the diff didn't show the `if`s by default. No need to rollback.
 
> The issue you are mentioned, [SUSE/spacewalk#22170](https://github.com/SUSE/spacewalk/issues/22170) doesn't apply in all cases for SUSE Manager and Uyuni.
> 
> EoL products are to be removed from both SUSE Manager and Uyuni. Architectures, not always.

This part is still valid.

FMPOV, this PR can just be closed, unless I am missing something.

2023-09-05 08:54 UTC, closed without merging