CCG salt jinja templating #16905 keichwa (#2420)
uyuni-project/uyuni-docs pull request #2430
Opened 2023-09-04 13:52 UTC by keichwa

# Description
* Jinja templating on Salt Clients https://github.com/SUSE/spacewalk/issues/16905
* Update modules/client-configuration/pages/configuration-management.adoc

# Target branches

Which documentation version does this PR apply to?

- [ ] Master (Default)
- [x] Manager-4.3
- [ ] Manager-4.2

# Links

Fixes #<insert issue or PR link, if any>

2023-09-04 13:54 UTC, keichwa commented on .changelog
> +  just examples.
```suggestion
- Explained that version numbers in SP upgrade in common-workflows are
  just examples.
```

2023-09-04 13:56 UTC, keichwa reviewed
remove unrelated changelog entry...

2023-09-11 14:18 UTC, 0rnela requested changes

2023-09-11 14:18 UTC, 0rnela commented on modules/client-configuration/pages/configuration-management.adoc
> +== Jinja templating on {salt} Clients
```suggestion
== Jinja templating on {salt} clients
```

2023-09-11 14:18 UTC, 0rnela commented on modules/client-configuration/pages/configuration-management.adoc
>  == Configuration File Macros on Traditional Clients
```suggestion
== Configuration file macros on traditional clients
```

2023-09-12 09:00 UTC, jcayouette approved these changes

2023-09-13 06:17 UTC, merged