fix ifeval white space and title style capitalization
uyuni-project/uyuni-docs pull request #2449
Opened 2023-09-14 05:53 UTC by keichwa

# Description

fix ifeval white space issue
unify title style capitalization

# Target branches

Which documentation version does this PR apply to?
- [ ] master (Default)
- [ ] manager-4.3

# Links
- Related development PR #<insert PR link, if any>
- Fixes #<insert spacewalk issue, if any>

2023-09-14 08:10 UTC, 0rnela requested changes

2023-09-14 08:10 UTC, 0rnela commented on modules/installation-and-upgrade/pages/proxy-container-installation.adoc
> +
```suggestion
```

2023-09-14 11:26 UTC, jcayouette approved these changes

2023-09-18 13:49 UTC, keichwa commented on modules/installation-and-upgrade/pages/proxy-container-installation.adoc
> +
no, this PR is about to add these white spaces to avoid github check errors ;)

2023-09-18 13:50 UTC, merged