Iau server upgrade #1214471 (#2441)
uyuni-project/uyuni-docs pull request #2480
Opened 2023-09-27 09:52 UTC by keichwa

# Description

* incomplete rename; new name: upgrade-intro.adoc
* use examples according to https://bugzilla.suse.com/show_bug.cgi?id=1214471

# Target branches

Which documentation version does this PR apply to?
- [ ] master (Default)
- [ ] manager-4.3

# Links
- Related development PR #<insert PR link, if any>
- Fixes #<insert spacewalk issue, if any>

2023-09-27 09:54 UTC, keichwa commented on .changelog
> +  Installation and Upgrade Guide
```suggestion
```

2023-09-27 09:56 UTC, keichwa commented on modules/installation-and-upgrade/pages/server-intro.adoc
> +* From version 3.2 to 4.0 or to 4.1 (upgrading directly from 3.2 to 4.2 or later is s not supported).
```suggestion
* From version 3.2 to 4.0 or to 4.1 (upgrading directly from 3.2 to 4.2 or later is not supported).
```

2023-09-27 14:39 UTC, keichwa commented on .changelog
> +  in the Installation and Upgrade Guide
```suggestion
  in the Installation and Upgrade Guide (bsc#1214471)
```

2023-10-02 12:07 UTC, 0rnela requested changes

2023-10-02 12:07 UTC, 0rnela commented on modules/installation-and-upgrade/pages/server-intro.adoc
> +The version number below are just examples.
```suggestion
The version numbers below are just examples.
```

2023-10-02 12:07 UTC, 0rnela commented on modules/installation-and-upgrade/pages/server-intro.adoc
> +{suse} uses these numbers for illustrative purposes only!
```suggestion
{suse} uses these numbers for illustrative purposes only.
```

2023-10-02 12:07 UTC, 0rnela commented on modules/installation-and-upgrade/pages/server-intro.adoc
> +Such a major upgrade usually is an upgrade from X.Y to X+1.0 or to X+1.1, where Y is the latest minor version of the X series.
```suggestion
Major upgrade is usually an upgrade from X.Y to X+1.0 or to X+1.1, where Y is the latest minor version of the X series.
```

2023-10-02 12:07 UTC, 0rnela commented on modules/installation-and-upgrade/pages/server-intro.adoc
> +Upgrading to the next minor version.
```suggestion
Minor upgrade refers to upgrading to the next minor version, from X.Y to X.Y+1.
```

2023-10-02 12:07 UTC, 0rnela commented on modules/installation-and-upgrade/pages/server-intro.adoc
> +Such a minor upgrade is an upgrade from X.Y to X.Y+1.
```suggestion
```

2023-10-02 12:13 UTC, 0rnela requested changes

2023-10-02 12:13 UTC, 0rnela commented on modules/installation-and-upgrade/pages/server-intro.adoc
> +If you take a closer look, you always upgrade from and to the latest patch level of the minor version.
```suggestion
[IMPORTANT]
====
You always upgrade from and to the latest patch level of the minor version.
====
```

2023-10-02 12:13 UTC, 0rnela commented on modules/installation-and-upgrade/pages/server-y.adoc
>  == Preparing Upgrade to 4.3
```suggestion
== Preparing the upgrade to 4.3
```

2023-10-02 12:13 UTC, 0rnela commented on modules/installation-and-upgrade/pages/server-x.adoc
>  = Server - Major Version Upgrade (X Upgrade)
```suggestion
= Server - Major version upgrade (X upgrade)
```

2023-10-02 12:13 UTC, 0rnela commented on modules/installation-and-upgrade/pages/server-y-zypper.adoc
>  = Server - Minor Version Upgrade with Zypper
```suggestion
= Server - Minor version upgrade with ``zypper``
```

2023-10-02 12:13 UTC, 0rnela commented on modules/installation-and-upgrade/pages/server-y-zypper.adoc
>  .Procedure: Upgrading with Zypper
```suggestion
.Procedure: Upgrading with ``zypper``
```

2023-10-02 12:13 UTC, 0rnela commented on modules/installation-and-upgrade/pages/upgrade-intro.adoc
> += Upgrade Intro
```suggestion
= Upgrade introduction
```

2023-10-04 08:36 UTC, 0rnela approved these changes

2023-10-09 08:43 UTC, merged