Ccg trad 2 salt #22376 keichwa
uyuni-project/uyuni-docs pull request #2483
Opened 2023-09-28 10:20 UTC by keichwa

# Description

https://github.com/SUSE/spacewalk/issues/22376

# Target branches

Which documentation version does this PR apply to?
- [x] master (Default)
- [ ] manager-4.3

# Links
- Related development PR #<insert PR link, if any>
- Fixes #<insert spacewalk issue, if any>

2023-09-28 10:39 UTC, keichwa commented
Note, in its current incarnation, we probably can backport this PR to 4.3 painlessly.  Later, on 5.0, we must check whether the default bootstrap script (template) has changes with the variable names, etc.  Additionally, we must check the Web UI for editing the bootstrap script.

2023-10-02 09:02 UTC, 0rnela requested changes

2023-10-02 09:02 UTC, 0rnela commented on modules/client-configuration/pages/contact-methods-migrate-traditional.adoc
> +.Procedure: Running the Bootstrap Script
```suggestion
.Procedure: Running the bootstrap script
```

2023-10-02 12:02 UTC, 0rnela approved these changes

2023-10-09 10:20 UTC, keichwa commented on .changelog
> +  /var/spacewalk in Installation and Upgrade Guide
```suggestion
```

2023-10-09 10:20 UTC, keichwa commented on .changelog
> -  Installation and Upgrade Guide
```suggestion
- Update Hardware Requirements section about disk space for
  /var/spacewalk in Installation and Upgrade Guide
```

2023-10-12 11:37 UTC, admd approved these changes
This looks good Karl. Thank you.

2023-10-12 11:37 UTC, admd commented on modules/client-configuration/pages/contact-methods-migrate-traditional.adoc
> +To migrate a system from a traditional client to a {salt}, the use can create the {salt} bootstrap script and re-register the client system with it.
```suggestion
To migrate a system from a traditional client to a {salt}, user can create the {salt} bootstrap script and re-register the client system with it.
```

2023-10-16 08:35 UTC, merged