4.3.7 SP5 patch jcayouette (#2381)
uyuni-project/uyuni-docs pull request #2496
Opened 2023-10-04 15:21 UTC by keichwa

* update

* adjusted versioning

* Update install-vm.adoc

# Description

Short summary of why you created this PR (if you added documentation, please add any relevant diagram).

# Target branches

Which documentation version does this PR apply to?
- [ ] master (Default)
- [ ] manager-4.3

# Links
- Related development PR #<insert PR link, if any>
- Fixes #<insert spacewalk issue, if any>

2023-10-04 15:32 UTC, keichwa commented on .changelog
> +- 4.3 based on SLE 15 SP5
```suggestion
- SUSE Manager 4.3 is based on SUSE Linux Enterprise 15 SP5; changed installation
  procedure accordingly
```

2023-10-04 15:40 UTC, raulillo82 requested changes
I might've found an error or at least an unfortunate typo.

2023-10-04 16:15 UTC, keichwa commented
Grrh, yes, this was a super stupid typo ;-(  I'll check the other 2...

2023-10-04 17:39 UTC, keichwa commented on modules/installation-and-upgrade/pages/proxy-registration.adoc
> +* SLE-Module-Server-Applications15-SP4-Updates
```suggestion
* SLE-Module-Basesystem15-{sp-base}-Pool
* SLE-Module-Basesystem15-{sp-base}-Updates
* SLE-Module-Server-Applications15-{sp-base}-Pool
* SLE-Module-Server-Applications15-{sp-base}-Updates
```

2023-10-04 17:39 UTC, keichwa commented on modules/quickstart/pages/quickstart-install-suma-proxy.adoc
> +* SLE-Module-Server-Applications15-SP4-Updates
```suggestion
* SLE-Module-Basesystem15-{sp-base}-Pool
* SLE-Module-Basesystem15-{sp-base}-Updates
* SLE-Module-Server-Applications15-{sp-base}-Pool
* SLE-Module-Server-Applications15-{sp-base}-Updates
```

2023-10-05 11:14 UTC, deneb-alpha requested changes
left one suggestion about using  `{productnumber}` instead  of hardcoded `4.3`

2023-10-05 11:14 UTC, deneb-alpha commented on modules/installation-and-upgrade/pages/proxy-registration.adoc
>  * SLE-Module-SUSE-Manager-Proxy-4.3-Updates
```suggestion
* SLE-Module-SUSE-Manager-Proxy-{productnumber}-Pool
* SLE-Module-SUSE-Manager-Proxy-{productnumber}-Updates
```

2023-10-05 11:14 UTC, deneb-alpha commented on modules/quickstart/pages/quickstart-install-suma-proxy.adoc
>  * SLE-Module-SUSE-Manager-Proxy-4.3-Updates
```suggestion
* SLE-Module-SUSE-Manager-Proxy-{productnumber}-Pool
* SLE-Module-SUSE-Manager-Proxy-{productnumber}-Updates
```

2023-10-05 11:59 UTC, deneb-alpha approved these changes
LGTM, thanks

2023-10-05 12:00 UTC, deneb-alpha commented
> left one suggestion about using `{productnumber}` instead of hardcoded `4.3`

as discussed. this will be done in a different card, not now

2023-10-05 13:13 UTC, jcayouette approved these changes

2023-10-05 13:20 UTC, raulillo82 approved these changes

2023-10-05 13:48 UTC, merged