Port43 sle15sp4 #2381 keichwa
uyuni-project/uyuni-docs pull request #2497
Opened 2023-10-04 15:37 UTC by keichwa

# Description

- SUSE Manager 4.3 is based on SUSE Linux Enterprise 15 SP5; changed installation procedure accordingly.

# Target branches

Which documentation version does this PR apply to?
- manager-4.3

# Links
- Related development PR #<insert PR link, if any>
- Fixes #<insert spacewalk issue, if any>

2023-10-04 16:42 UTC, deneb-alpha commented
we also have a bsc for this very same issue:
* https://github.com/SUSE/spacewalk/issues/22090
* https://bugzilla.suse.com/show_bug.cgi?id=1213469

2023-10-04 16:45 UTC, deneb-alpha requested changes
sent some suggestions

2023-10-04 16:45 UTC, deneb-alpha commented on .changelog
> +  installation procedure accordingly
```suggestion
- SUSE Manager 4.3 is based on SUSE Linux Enterprise 15 SP4; changed
  installation procedure accordingly (bsc#1213469)
```

2023-10-04 17:07 UTC, keichwa commented on modules/installation-and-upgrade/pages/proxy-registration.adoc
> +* SLE-Module-Server-Applications15-SP4-Updates
yes, looks save.

2023-10-04 17:07 UTC, deneb-alpha commented
> # Description
> * SUSE Manager 4.3 is based on SUSE Linux Enterprise 15 SP5; changed installation procedure accordingly.

is based on SUSE Linux Enterprise 15 SP4

2023-10-04 18:24 UTC, deneb-alpha commented on modules/installation-and-upgrade/pages/install-vm.adoc
> +SUSEConnect -p sle-module-suse-manager-server/
on the proxy string for suseconnect, I don't  know why  you removed the  productnumber and the  arch. 

looking at  parameters.yml the  variable could  be
`smrproductnumber`

2023-10-05 09:39 UTC, 0rnela requested changes

2023-10-05 09:39 UTC, 0rnela commented on modules/installation-and-upgrade/pages/install-vm.adoc
> +SUSEConnect -p sle-module-suse-manager-server/
```suggestion
SUSEConnect -p sle-module-suse-manager-server/{smrproductnumber}/x86_64
```

2023-10-05 09:43 UTC, 0rnela commented on .changelog
> +- Documented Debian 12 as a supported client OS in Client Configuration
```suggestion
- Added Debian 12 as a a technology preview client in Client Configuration Guide
```

2023-10-05 09:46 UTC, 0rnela approved these changes

2023-10-05 09:46 UTC, jcayouette approved these changes

2023-10-05 11:16 UTC, deneb-alpha requested changes
left a suggestion about using `{productnumber}` instead of hardcoded `4.3`

2023-10-05 11:16 UTC, deneb-alpha commented on modules/installation-and-upgrade/pages/proxy-registration.adoc
>  * SLE-Module-SUSE-Manager-Proxy-4.3-Updates
```suggestion
* SLE-Module-SUSE-Manager-Proxy-{productnumber}-Pool
* SLE-Module-SUSE-Manager-Proxy-{productnumber}-Updates
```

2023-10-05 11:16 UTC, deneb-alpha commented on modules/quickstart/pages/quickstart-install-suma-proxy.adoc
>  * SLE-Module-SUSE-Manager-Proxy-4.3-Updates
```suggestion
* SLE-Module-SUSE-Manager-Proxy-{productnumber}-Pool
* SLE-Module-SUSE-Manager-Proxy-{productnumber}-Updates
```

2023-10-05 12:01 UTC, deneb-alpha approved these changes
LGTM, thanks

2023-10-05 12:01 UTC, deneb-alpha commented
> left a suggestion about using `{productnumber}` instead of hardcoded `4.3`

as discussed, this will be done in a different card

2023-10-05 13:44 UTC, merged