Amended the openSUSE Channels table for openSUSE Leap Micro clients
uyuni-project/uyuni-docs pull request #2627
Opened 2023-11-21 10:09 UTC by 0rnela

# Description

Fixed the old table listing openSUSE Channels - CLI, which was was incomplete.

# Target branches

* Which documentation version does this PR apply to?
* Does this content need to be backported? If this is the case, create an issue for tracking it and add the link to this PR.
* Whenever possible, cross-reference each backport PR here, so that all backports can be easily accessed from the description.

- [x] master
- [ ] manager-4.3

# Links
- This PR tracks issue #<insert spacewalk issue, if any>
- Related development PR #<insert PR link, if any>

2023-11-21 12:07 UTC, nodeg reviewed
LGTM, however I cannot imagine how the rendered version does look like.

2023-11-21 12:51 UTC, keichwa requested changes
I guess there were 2 c&p errors.

2023-11-21 14:09 UTC, 0rnela commented
> LGTM, however I cannot imagine how the rendered version does look like.
@nodeg 
![4illustration](https://github.com/uyuni-project/uyuni-docs/assets/12948974/cf443062-55b3-403d-b827-3b5ab2b968c6)

2023-11-22 10:43 UTC, keichwa requested changes
Maybe, sth went wrong.  Hope I got it right this time.

2023-11-22 10:43 UTC, keichwa commented on modules/client-configuration/pages/clients-opensuseleapmicro.adoc
>  | Base Channel             | opensuse_micro5_5                  | opensuse_micro5_5              | opensuse_micro5_3
```suggestion
| Base Channel             | opensuse_micro5_5                  | opensuse_micro5_4              | opensuse_micro5_3
```

2023-11-22 10:43 UTC, keichwa commented on modules/client-configuration/pages/clients-opensuseleapmicro.adoc
>  | Client Channel           | opensuse_micro5_5-uyuni-client     | opensuse_micro5_4-uyuni-client | opensuse_micro5_4-uyuni-client
```suggestion
| Client Channel           | opensuse_micro5_5-uyuni-client     | opensuse_micro5_4-uyuni-client | opensuse_micro5_3-uyuni-client
```

2023-11-22 16:14 UTC, keichwa approved these changes

2023-11-22 17:19 UTC, merged