CCG remove traditional clients feature #18879 (the rest)
uyuni-project/uyuni-docs pull request #2628
Opened 2023-11-21 13:12 UTC by keichwa

https://github.com/SUSE/spacewalk/issues/18879

*Before you submit this PR make sure you have added an entry to **.changelog** file.*

# Description

Short summary of why you created this PR (if you added documentation, please add any relevant diagram).

# Target branches

* Which documentation version does this PR apply to?
* Does this content need to be backported? If this is the case, create an issue for tracking it and add the link to this PR.
* Whenever possible, cross-reference each backport PR here, so that all backports can be easily accessed from the description.

- [ ] master
- [ ] manager-4.3

# Links
- This PR tracks issue #<insert spacewalk issue, if any>
- Related development PR #<insert PR link, if any>

2023-11-21 14:53 UTC, 0rnela requested changes

2023-11-21 14:53 UTC, 0rnela commented on modules/client-configuration/pages/registration-cli.adoc
> +== Salt Minion configuration
```suggestion
== {salt} Minion configuration
```

2023-11-22 07:27 UTC, keichwa commented on modules/client-configuration/pages/repositories.adoc
>  For example, when applying the highstate or performing a package action.
I think we better should keep sentences short.

2023-11-22 15:34 UTC, 0rnela requested changes

2023-11-22 15:34 UTC, 0rnela commented on modules/client-configuration/pages/registration-cli.adoc
>  == Manual Salt client registration
```suggestion
== Manual client registration
```

2023-11-22 15:34 UTC, 0rnela commented on modules/client-configuration/pages/registration-cli.adoc
> +== {salt} Minion configuration
```suggestion
== Client configuration
```

2023-11-22 15:34 UTC, 0rnela commented on modules/client-configuration/pages/registration-cli.adoc
> +{salt} Minion ([package]``salt-minion``)::
```suggestion
Client ([package]``salt-minion``)::
```

2023-11-22 15:34 UTC, 0rnela commented on modules/client-configuration/pages/system-types.adoc
> +Base system types include ``Salt`` for Salt clients.
```suggestion
Base system type is ``Salt`` for all clients.
```

2023-11-23 12:57 UTC, merged