whitespace issues (ifeval warning)
uyuni-project/uyuni-docs pull request #2632
Opened 2023-11-22 16:05 UTC by keichwa

* empty line before and after conditional statement
* use nbsp to connect version number with product name

*Before you submit this PR make sure you have added an entry to **.changelog** file.*

# Description

Short summary of why you created this PR (if you added documentation, please add any relevant diagram).

# Target branches

* Which documentation version does this PR apply to?
* Does this content need to be backported? If this is the case, create an issue for tracking it and add the link to this PR.
* Whenever possible, cross-reference each backport PR here, so that all backports can be easily accessed from the description.

- [ ] master
- [ ] manager-4.3

# Links
- This PR tracks issue #<insert spacewalk issue, if any>
- Related development PR #<insert PR link, if any>

2023-11-22 17:44 UTC, juliogonzalez approved these changes
I understand the problem with the ifeval, but I am not sure I am understanting the fixes in lines 20 21... they look the same before and after the change?

2023-11-23 06:38 UTC, keichwa commented
Julio González Gil ***@***.***> writes:

> I understand the problem with the ifeval, but I am not sure I am
> understanting the fixes in lines 20 21... they look the same before
> and after the change?

These are no-breaking spaces (unicode: " " / HTML entity: "&nbsp;" /
adoc macro: "{nbsp}").  I usually enter the Unicode char directly,
and my editor displays it as a colored underline.  Thus I can see it.

I admit that can be confusing.  I'll avoid it in the future here.

-- 
Karl Eichwalder

2023-11-23 11:15 UTC, 0rnela requested changes

2023-11-23 11:15 UTC, 0rnela commented on modules/client-configuration/pages/clients-amazon.adoc
> +When created at AWS, {amazon} 2 instances always have the same `machine-id` id at `/etc/machine-id`.
```suggestion
When created at {aws}, {amazon} 2 instances always have the same `machine-id` id at `/etc/machine-id`.
```

2023-11-23 11:30 UTC, merged