Troubleshoot public cloud setup with BYOS instances -AWS- tapasn
uyuni-project/uyuni-docs pull request #2714
Opened 2024-01-15 13:38 UTC by bashlion

*Before you submit this PR make sure you have added an entry to **.changelog** file.*

# Description

Short summary of why you created this PR (if you added documentation, please add any relevant diagram).

# Target branches

* Which documentation version does this PR apply to?
* Does this content need to be backported? If this is the case, create an issue for tracking it and add the link to this PR.
* Whenever possible, cross-reference each backport PR here, so that all backports can be easily accessed from the description.

- [ ] master
- [ ] manager-4.3

# Links
- This PR tracks issue #<insert spacewalk issue, if any>
- Related development PR #<insert PR link, if any>

2024-01-15 13:52 UTC, keichwa commented
Thanks, it looks good in general (we could do some style adjustments as a separate PR later).  @jcayouette , I'd appreciate if you'd take a look first.

2024-01-17 15:41 UTC, 0rnela requested changes
Thank you for the PR. Please check the suggestions.

2024-01-17 15:41 UTC, 0rnela commented on modules/administration/pages/troubleshooting/tshoot-suma-installation-public-cloud.md
> +#### **Troubleshooting Issues while setting up SUSE Manager with separate disk for data in Public Cloud (BYOS)**
```suggestion
= Setting up SUSE Manager with separate disk for data in Public Cloud (BYOS)

```

2024-01-17 15:41 UTC, 0rnela commented on modules/administration/pages/troubleshooting/tshoot-suma-installation-public-cloud.md
> +SUSE Manager setup errors out while restarting services step during setup.
```suggestion
{productname} setup results with an error while restarting services during setup. 

```

2024-01-17 15:41 UTC, 0rnela commented on modules/administration/pages/troubleshooting/tshoot-suma-installation-public-cloud.md
> +The set up gets failed on restarting Tomcat.
```suggestion
The set up failes on restarting tomcat.

```

2024-01-17 15:41 UTC, 0rnela commented on modules/administration/pages/troubleshooting/tshoot-suma-installation-public-cloud.md
> +When SUSE Manager is setup using separate disks for cache, pgsql and spacewalk. The already present data within these partitions are covered under the new mount point.
```suggestion
When {productname} is set up using separate disks for cache, pgsql and spacewalk, the already present data within these partitions are covered under the new mount point.

```

2024-01-17 15:41 UTC, 0rnela commented on modules/administration/pages/troubleshooting/tshoot-suma-installation-public-cloud.md
> +Because of which data for certain services like tomcat goes missing due to broken symlink.
```suggestion
Because of this data for certain services like tomcat go missing due to a broken symbolic link.

```

2024-01-17 15:41 UTC, 0rnela commented on modules/administration/pages/troubleshooting/tshoot-suma-installation-public-cloud.md
> +As SUSE Manager instance of cloud already have some services setup these data when not available during setup causes the service to not restart as expected and the setup to fail in turn.
```suggestion
As {productname} instance of cloud already has some services set up, when the data is not available during set up it causes the service to not restart as expected. 
Therefore the set up fails.

```

2024-01-17 15:41 UTC, 0rnela commented on modules/administration/pages/troubleshooting/tshoot-suma-installation-public-cloud.md
> +Actual Data which should be present:
```suggestion
Actual data which should be present:

```

2024-01-17 15:41 UTC, 0rnela commented on modules/administration/pages/troubleshooting/tshoot-suma-installation-public-cloud.md
> +1. SUSE Manager Server Provisioned in AWS using relevant AMI for BYOS
```suggestion
1. {productname} server provisioned in {aws} uses relevant AMI for {byos}

```

2024-01-17 15:43 UTC, 0rnela commented on CHANGELOG.md
> +- Added a troubleshooting Document under the troubleshooting page showing how to troubleshoot setup issues in public cloud setup (BYOS)
```suggestion
- Added troubleshooting instructions for the set up issues in public cloud ({byos}) to Administration Guide
```

2024-01-18 14:57 UTC, keichwa requested changes
@0rnela I committed many of your suggestions. Some other I edited.  I'd appreciated if you'd review my proposals, and commit what's appropriate.
If possibile @bashlion could please finally check and hopefully approve the result.

2024-01-18 15:37 UTC, 0rnela approved these changes

2024-01-18 15:48 UTC, keichwa approved these changes

2024-01-22 10:19 UTC, 0rnela commented
@jcayouette - can you to please review this PR?

2024-01-22 10:37 UTC, jcayouette approved these changes

2024-01-29 08:15 UTC, keichwa approved these changes

2024-01-29 08:15 UTC, keichwa commented on modules/administration/pages/troubleshooting/tshoot-suma-installation-public-cloud.md
> +When {productname} is set up using separate disks for cache, pgsql and spacewalk, the already present data within these partitions are covered under the new mount point.
```suggestion
When {productname} is set up using separate disks for cache, pgsql and spacewalk, the existing data within these partitions are covered under the new mount point.
```

2024-01-29 08:15 UTC, keichwa commented on modules/administration/pages/troubleshooting/tshoot-suma-installation-public-cloud.md
> +The set up fails on restarting Tomcat.
```suggestion
The setup fails on restarting Tomcat.

```

2024-01-29 08:15 UTC, keichwa commented on modules/administration/pages/troubleshooting/tshoot-suma-installation-public-cloud.md
> +When using {procustname} in public cloud with separate data partitions, make sure that the already present data in those directories are copied onto the new partition.
```suggestion
When using {procustname} in public cloud with separate data partitions, make sure that the existing data in those directories are copied onto the new partition.
```

2024-01-31 10:25 UTC, merged