Ccg migrate el 2 sll #23428
uyuni-project/uyuni-docs pull request #2737
Opened 2024-01-30 13:47 UTC by keichwa

# Some hints

Consider adding an entry to the `CHANGELOG.md` file in the toplevel directory.
In the `manager-4.3`, the hidden `.changelog` file with a leading dot is still in use.

Add Description, Target branches, and related Links below the following section titles.

In the Description, just enter a summary of why you created this PR (and, if available, add any relevant diagram).

# Description

Short summary of why you created this PR (if you added documentation, please add any relevant diagram).

# Target branches

* Which product version this PR applies to (Uyuni, SUMA 4.3, SUMA MU X.Y.Z, or SUMA development version).  This information can be helpful if `ifeval` statements are needed to publish it for certain products only.
* Does this PR need to be backported? If yes, create an issue for tracking it and add the link to this PR.
* Whenever possible, cross-reference each backport PR here, so that all backports can be easily accessed from the description.

Backport targets (edit as needed):

- master
- 4.3

# Links
- This PR tracks issue #<insert spacewalk issue, if any>
- Related development PR #<insert PR link, if any>

2024-01-30 13:54 UTC, keichwa commented
[suse-manager.tar.gz](https://github.com/uyuni-project/uyuni-docs/files/14099068/suse-manager.tar.gz)
[en.tar.gz](https://github.com/uyuni-project/uyuni-docs/files/14099071/en.tar.gz)

HTML output:
[suse-manager.tar.gz](https://github.com/uyuni-project/uyuni-docs/files/14054227/suse-manager.tar.gz)
[en.tar.gz](https://github.com/uyuni-project/uyuni-docs/files/14054231/en.tar.gz)
It unpacks into directory en. Thus better create some temp first and change to it:
```
mkdir TEMP
cd TEMP
tar xvf .../suse-manager.tar.gz
tar xvf .../en.tar.gz
$BROWSER fien/suse-manager/client-configuration/clients-sleses.html#clients-sleses-el-migration
```
I added a (currently commented) procedure.  I do not know whether it's correct and whether we need it at all.

2024-01-30 14:02 UTC, 0rnela requested changes

2024-01-30 14:02 UTC, 0rnela commented on CHANGELOG.md
> +- Added section about migrating EL clients to SUSE Liberty Linux to
```suggestion
- Added section about migrating extended life clients to SUSE Liberty Linux to
```

2024-01-30 14:02 UTC, 0rnela commented on modules/client-configuration/pages/clients-sleses.adoc
> +== Migrate EL clients to {sll}
```suggestion
== Migrate Extended Life Clients to {sll}
```

2024-01-30 14:02 UTC, 0rnela commented on modules/client-configuration/pages/clients-sleses.adoc
> +If an EL client such as RHEL and all clones (like {centos}, {almalinux}, {rocky}, and {oracle}) is already registered as a minion on {productname} and users wanted to migrate it to {sll} they can use
```suggestion
If an extended life (EL) client such as RHEL and all clones (like {centos}, {almalinux}, {rocky}, and {oracle}) is already registered as a minion on {productname} and users wanted to migrate it to {sll} they can use a re-activation key to apply the activation key that drives the migration.
```

2024-01-30 17:01 UTC, rjmateus commented on modules/client-configuration/pages/clients-sleses.adoc
> +. In the {webui}, navigate to menu:Salt[Keys], locate the Salt key associated with the existing client, and click btn:[delete].
we dont' need to delete the key. In face I don't know what the side effect it can have

2024-01-30 17:02 UTC, rjmateus commented on modules/client-configuration/pages/clients-sleses.adoc
> +// FIXME
I don't think we need this section. The one above should be enough

2024-01-30 17:04 UTC, rjmateus commented on modules/client-configuration/pages/clients-sleses.adoc
> +
After changing this file, the salt-client server needs to be restarted.
`systemctl restart venv-salt-minon`

or for legacy salt:
`systemctl restart salt-minon`

2024-01-31 06:04 UTC, keichwa commented on modules/client-configuration/pages/clients-sleses.adoc
> +== Migrate Extended Life Clients to {sll}
```suggestion
== Migrate Enterprise Linux (EL) clients to {sll}
```

2024-01-31 06:06 UTC, keichwa commented on CHANGELOG.md
> +  Client Configuration Guide
```suggestion
- Added section about migrating Enterprise Linux (EL) clients to SUSE Liberty
  Linux to Client Configuration Guide
```

2024-01-31 06:36 UTC, keichwa commented
New HTML output; use it as described above.

[suse-manager.tar.gz](https://github.com/uyuni-project/uyuni-docs/files/14108095/suse-manager.tar.gz)

2024-01-31 09:00 UTC, mackdk approved these changes
LGTM

2024-01-31 09:53 UTC, jcayouette approved these changes

2024-01-31 09:55 UTC, rjmateus approved these changes
LGTM

2024-01-31 11:01 UTC, merged