Container installation jcayouette
uyuni-project/uyuni-docs pull request #2745
Opened 2024-01-31 12:50 UTC by jcayouette

# Some hints

Consider adding an entry to the `CHANGELOG.md` file in the toplevel directory.
In the `manager-4.3`, the hidden `.changelog` file with a leading dot is still in use.

**WIP**

**During work on this task I removed "release.key" files. When you review this PR select filter (upper left) and select deleted files. This will reduce the content you have to browse through**

Container installation docs.  To support new container deployment features for both Uyuni and SUMA 5.0

## Task Overview

- [ ] Uyuni will contain legacy installation documentation along side the new container deployment. 
- [ ] SUMA 5.0 will include containerized deployment documentation while deprecating legacy installation documentation)

## Work in progress

- [x] Includes podman installation (For both suma and uyuni **ifdef required**)
- [x] Uyuni container utiliies installation (for both suma and uyuni **ifdef required**)
- [x] Persistent volumes 
- [x] Uyuni deployment as a container
- [ ] SUMA deployment as a container
  * Sle micro IN_PROGRESS
  * SLES IN_PROGRESS
- [ ] Migration docs from servers older than:
  * yyyy.mm : **Uyuni ifdef required**
  * 4.3 : **SUMA ifdef required**
- [ ] K3s (Uyuni only) 
- [ ] RKE2 (Uyuni only)
- [ ] Update changelog

# Target branches

- master (Uyuni)
- manager-5.0

# Links
https://github.com/uyuni-project/uyuni/tree/master/containers/doc
https://github.com/uyuni-project/uyuni-docs/pull/2190
https://github.com/SUSE/spacewalk/issues/22105
https://github.com/SUSE/spacewalk/issues/23125#issuecomment-1894327395

2024-02-05 08:47 UTC, keichwa requested changes
I'll continue later.

2024-02-05 08:47 UTC, keichwa commented on modules/installation-and-upgrade/pages/container-deployment/deploy-as-a-container.adoc
> +In this section, you will gain expertise in setting up and deploying a {productname} Server. The process encompasses the installation of [command]``Podman``, [filename]``Uyuni container utilities``,
```suggestion
In this section, you will gain expertise in setting up and deploying a {productname} Server.
The process encompasses the installation of [command]``Podman``, [systemitem]``Uyuni container utilities``, deployment, and then initiating interaction with the container through [command]``mgrctl``.
```

2024-02-05 08:47 UTC, keichwa commented on modules/installation-and-upgrade/pages/container-deployment/deploy-as-a-container.adoc
> +It is important to note that this section assumes you have already configured a {tumbleweed} or {opensuse} {opensuse-version} server, whether it's running on a physical machine or within a virtual en
```suggestion
[NOTE]
====
This section assumes you have already configured a {tumbleweed} or {opensuse} {opensuse-version} server, whether it is running on a physical machine or within a virtual environment.
====
```

2024-02-05 08:47 UTC, keichwa commented on modules/installation-and-upgrade/pages/container-deployment/deploy-as-a-container.adoc
> +. Zypper will download and install [command]``Podman`` along with its dependencies.
```suggestion
+

Zypper will download and install [command]``Podman`` along with its dependencies.
```
This is not a separate step, but result of the previous one ;)

2024-02-05 08:47 UTC, keichwa commented on modules/installation-and-upgrade/pages/container-deployment/deploy-as-a-container.adoc
> +. Once the installation is complete, verify that [command]``Podman`` is installed by running:
```suggestion
. When the installation is complete, verify that [command]``Podman`` is installed by running:
```

2024-02-05 08:47 UTC, keichwa commented on modules/installation-and-upgrade/pages/container-deployment/deploy-as-a-container.adoc
> +For more information see, link:https://podman.io/[https://podman.io]
```suggestion
For more information, see https://podman.io/.
```

2024-02-13 09:04 UTC, jcayouette commented
This still needs a lot of work but since it is merging to master for Beta 1 I will merge for now and continue working on it. We can review the next PR.

2024-02-13 09:04 UTC, merged