Remove now useless proxy install part in setup page
uyuni-project/uyuni-docs pull request #2940
Opened 2024-04-12 09:41 UTC by cbosdo

# Description

Remove deprecated parts for proxy setup page.

# Target branches

Backport targets (edit as needed):

- master 

# Links
- This PR tracks issue #<insert spacewalk issue, if any>
- Related development PR #<insert PR link, if any>

2024-04-15 07:09 UTC, keichwa requested changes
plus a drive-by edit.

2024-04-15 07:09 UTC, keichwa commented on modules/installation-and-upgrade/pages/proxy-container-setup.adoc
>  Both [literal]``spacecmd``command  and web UI ways generate configuration archive. This archive needs to be made available on container host.
```suggestion
Both [command]``spacecmd`` command  and {webui} ways generate a configuration archive.
This archive needs to be made available on container host.
```

2024-04-15 07:09 UTC, keichwa commented on modules/installation-and-upgrade/pages/proxy-container-setup.adoc
> +Follow the installation instructions to use the archive to get the proxy containers: xref:reference:proxy-container-installation.adoc[].
```suggestion
For installation instructions to use the archive to get the proxy containers, see xref:reference:proxy-container-installation.adoc[].
```

2024-04-17 08:17 UTC, keichwa approved these changes
Thank you!

2024-04-22 06:08 UTC, jcayouette approved these changes

2024-04-22 06:11 UTC, merged