document how to mirror Ubuntu ESM packages
uyuni-project/uyuni-docs pull request #2972
Opened 2024-04-30 08:50 UTC by stdevel

# Some hints

Consider adding an entry to the `CHANGELOG.md` file in the toplevel directory.
Cosmetic changes such as fixing typos do not need log entries (nevertheless it is important to fix typos, etc.)!
In the `manager-4.3`, the hidden `.changelog` file with a leading dot is still in use.

Add Description, Target branches, and related Links below the following section titles.

In the Description, just enter a summary of why you created this PR (and, if available, add any relevant diagram).

# Description

This PR documents how to mirror Ubuntu Pro packages, see also issue #2971

# Target branches

* Which product version this PR applies to (Uyuni, SUMA 4.3, SUMA MU X.Y.Z, or SUMA development version).  This information can be helpful if `ifeval` statements are needed to publish it for certain products only.
* Does this PR need to be backported? If yes, create an issue for tracking it and add the link to this PR.
* Whenever possible, cross-reference each backport PR here, so that all backports can be easily accessed from the description.

Backport targets (edit as needed):

- master
- 4.3

# Links

- This PR tracks issue #2971

2024-05-02 09:29 UTC, 0rnela requested changes

2024-05-02 09:29 UTC, 0rnela commented on modules/client-configuration/pages/clients-ubuntu.adoc
> +Canonical provides https://ubuntu.com/security/esm[Expanded Security Maintenance] (**ESM**) packages for https://ubuntu.com/pro[Ubuntu Pro] users and customers. These packages offer longer maintenanc
```suggestion
Canonical provides https://ubuntu.com/security/esm[Expanded Security Maintenance] (**ESM**) packages for https://ubuntu.com/pro[Ubuntu Pro] users and customers. 
These packages offer longer maintenance (_10 to 12 years_) for several operating system components and selected applications.
```

2024-05-02 09:29 UTC, 0rnela commented on modules/client-configuration/pages/clients-ubuntu.adoc
> +
```suggestion


```

2024-05-02 09:29 UTC, 0rnela commented on modules/client-configuration/pages/clients-ubuntu.adoc
> +Register an Ubuntu host with Ubuntu Pro. You will find your personal registration token in the https://ubuntu.com/pro/dashboard[Ubuntu Pro Dashbaord]. An https://login.ubuntu.com/[Ubuntu One acconut]
```suggestion
Register an Ubuntu host with Ubuntu Pro. 
You will find your personal registration token in the https://ubuntu.com/pro/dashboard[Ubuntu Pro Dashbaord]. 
An https://login.ubuntu.com/[Ubuntu One acconut] is required for this.
```

2024-05-02 09:29 UTC, 0rnela commented on modules/client-configuration/pages/clients-ubuntu.adoc
> +One **dedicated bearer token** is used per repository.
```suggestion
One dedicated bearer token is used per repository.
```

2024-05-02 10:06 UTC, stdevel reviewed
Thanks for the suggesstions, I just applied them.

2024-05-06 06:39 UTC, keichwa commented on README.adoc
> + Write your changes to the `.changelog` file. New entries are added to the top, in the following format. Each collection of release entries should be separated by dashed lines. These lines are used t
```suggestion
 Write your changes to the `CHANGELOG.md` file. New entries are added to the top, in the following format. Each collection of release entries should be separated by dashed lines. These lines are used to extract the automated changelog notes for releases.
```

2024-05-06 06:39 UTC, keichwa commented on modules/client-configuration/pages/clients-ubuntu.adoc
> +sudo gpg --homedir /var/lib/spacewalk/gpgdir --import ubuntu-advantage-esm-*.gpg
I guess on SUMA 5.0 and containerized Uyuni, you must use `mgradm` now:

```suggestion
mgradm gpg add /path/to/gpg.key
```

See https://github.com/uyuni-project/uyuni-docs/pull/2982

2024-05-07 17:07 UTC, stdevel commented
Thanks for the feedback, I just applied your suggestions and fixed the merge conflict in `CHANGELOG.md`. Let me know, what you think. 🙂

2024-05-08 06:18 UTC, keichwa requested changes
In general and from my editor's POV, it looks good to me now.
We now also need a developer to take a look.  @juliogonzalez , can you somehow help with this?

2024-05-08 06:18 UTC, keichwa commented on .changelog
> +# - Fixed error in Bat section of Upgrade Guide (bsc#1234567)
File was created because of misleading (outdated) statements in the README file.  Can you please delete it again, if not already done?

2024-05-08 11:06 UTC, mcalmer approved these changes
LGTM

2024-05-08 12:27 UTC, merged