Install upgrade improvements jcayouette
uyuni-project/uyuni-docs pull request #3012
Opened 2024-05-13 11:11 UTC by jcayouette

# Proxy Migration

## Task
- [ ] Add Proxy migration task to docs (SUMA / Uyuni)

## Branches
- master

# Links
- https://github.com/SUSE/spacewalk/issues/23471#issuecomment-2018269415

2024-05-13 11:23 UTC, 0rnela approved these changes

2024-05-13 12:39 UTC, nodeg commented on modules/installation-and-upgrade/pages/container-deployment/suma/proxy-migration.adoc
> +// Add details on this transfer, filename and where it is located. `/root/ssl-build/`
The layout for this is broken when being rendered:
![image](https://github.com/uyuni-project/uyuni-docs/assets/12104291/794f8686-cb48-435d-940a-f3e89a63f85d)

2024-05-13 12:43 UTC, nodeg commented on modules/installation-and-upgrade/pages/container-deployment/suma/proxy-migration.adoc
> +.
The broken layout could be due to this extra dot.

2024-05-13 13:02 UTC, vandabarata commented
> As a first version, this looks quite good. However, we should keep in mind to not only explain how we can migrate a 4.3 containerized proxy, but also a regular 4.3 proxy to 5.0.

Yes, that is _really_ important, in my opinion. And that should also be covered here

2024-05-13 13:09 UTC, vandabarata commented on modules/installation-and-upgrade/pages/container-deployment/suma/proxy-migration.adoc
> +
After this, user still needs to migrate from systemd to mgrpxy - https://github.com/SUSE/spacewalk/issues/23471
![image](https://github.com/uyuni-project/uyuni-docs/assets/1148556/70f54ad4-4e13-43f7-a75f-bf64ed35e7ba)

2024-05-13 13:53 UTC, jcayouette commented on modules/installation-and-upgrade/pages/container-deployment/suma/proxy-migration.adoc
> +.
Known issue this section is still in progress. Thanks.

2024-05-14 09:57 UTC, vandabarata commented on modules/installation-and-upgrade/pages/container-deployment/suma/proxy-migration.adoc
> +. Next register this machine using your {productname} {productnumber} Proxy Extension code.
```suggestion
. Then register this machine using your {productname} {productnumber} Proxy Extension code.
```

2024-05-14 15:15 UTC, vandabarata requested changes

2024-05-14 15:15 UTC, vandabarata commented on modules/installation-and-upgrade/pages/container-deployment/suma/proxy-migration.adoc
> +mgrpxy install podman config.tar.gz
```suggestion
systemctl start uyuni-proxy-pod
```

2024-05-14 15:15 UTC, vandabarata commented on modules/installation-and-upgrade/pages/container-deployment/suma/proxy-migration.adoc
> +
```suggestion

. Enable the new Proxy with:
+ 

----
systemctl enable --now uyuni-proxy-pod
----

```

2024-05-14 15:15 UTC, vandabarata commented on modules/installation-and-upgrade/pages/container-deployment/suma/proxy-migration.adoc
> +.Task: Migrate {productname} 4.3 Proxy to {productname} {productnumber} Containerized Proxy
```suggestion
.Task: Migrate {productname} 4.3 Containerized Proxy to {productname} {productnumber} New Containerized Proxy
```

2024-05-15 08:09 UTC, merged