Update proxy-container-installation-uyuni.adoc
uyuni-project/uyuni-docs pull request #3023
Opened 2024-05-14 14:39 UTC by wtmpx

We haven't mention how to create custom volume.

# Some hints

Consider adding an entry to the `CHANGELOG.md` file in the toplevel directory.
Cosmetic changes such as fixing typos do not need log entries (nevertheless it is important to fix typos, etc.)!
In the `manager-4.3`, the hidden `.changelog` file with a leading dot is still in use.

Add Description, Target branches, and related Links below the following section titles.

In the Description, just enter a summary of why you created this PR (and, if available, add any relevant diagram).

# Description

Short summary of why you created this PR (if you added documentation, please add any relevant diagram).

# Target branches

* Which product version this PR applies to (Uyuni, SUMA 4.3, SUMA MU X.Y.Z, or SUMA development version).  This information can be helpful if `ifeval` statements are needed to publish it for certain products only.
* Does this PR need to be backported? If yes, create an issue for tracking it and add the link to this PR.
* Whenever possible, cross-reference each backport PR here, so that all backports can be easily accessed from the description.

Backport targets (edit as needed):

- master
- 4.3

# Links
- This PR tracks issue #<insert spacewalk issue, if any>
- Related development PR #<insert PR link, if any>

2024-05-15 05:02 UTC, keichwa requested changes
Cosmetic suggestions.

2024-05-15 05:02 UTC, keichwa commented on modules/installation-and-upgrade/pages/container-deployment/uyuni/proxy-container-installation-uyuni.adoc
> +podman volume create --driver local --opt device=/dev/mapper/uyuni--proxy-tftpboot --opt type=xfs uyuni-proxy-tftpboot
```suggestion
Run these commands to create custom volumes:

 ---- 
podman volume create --driver local --opt device=/dev/mapper/uyuni--proxy-rhn--cache --opt type=xfs uyuni-proxy-rhn-cache
podman volume create --driver local --opt device=/dev/mapper/uyuni--proxy-squid--cache --opt type=xfs uyuni-proxy-squid-cache
podman volume create --driver local --opt device=/dev/mapper/uyuni--proxy-tftpboot --opt type=xfs uyuni-proxy-tftpboot
----
```

2024-05-16 06:04 UTC, keichwa commented on modules/installation-and-upgrade/pages/container-deployment/uyuni/proxy-container-installation-uyuni.adoc
> + ----
```suggestion
---- 
```

2024-05-16 06:06 UTC, keichwa requested changes

2024-05-16 06:06 UTC, keichwa commented on modules/installation-and-upgrade/pages/container-deployment/uyuni/proxy-container-installation-uyuni.adoc
> + ----
```suggestion
----
```

2024-05-16 06:06 UTC, keichwa commented on modules/installation-and-upgrade/pages/container-deployment/uyuni/proxy-container-installation-uyuni.adoc
> +----
```suggestion
----
```

2024-05-16 06:08 UTC, keichwa approved these changes

2024-05-21 11:17 UTC, mbussolotto approved these changes
just a consideration about change `uyuni-proxy-systemd-services` in favor of `mgrpxy`. The rest seems fine

2024-05-21 11:17 UTC, mbussolotto commented on modules/installation-and-upgrade/pages/container-deployment/uyuni/proxy-container-installation-uyuni.adoc
> +By default, the [package]``uyuni-proxy-systemd-services`` package creates these three directories that can be used to mount external disks:
`uyuni-proxy-systemd-services` it's going to be deprecated. Better say something `mgrpxy` for uyuni (instead for 4.3 `uyuni-proxy-systemd-services`  is fine)

2024-05-27 13:29 UTC, merged