Update autoinstallation copy for containerized server
uyuni-project/uyuni-docs pull request #3047
Opened 2024-05-31 14:13 UTC by aaannz

# Description

This PR updates instruction how to register autoinstallation distribution with containerized server.

# Target branches

Uyuni, SUMA5

Backport targets (edit as needed):

- master

# Links
- This PR tracks issue https://github.com/SUSE/spacewalk/issues/24111
- Related development PR #<insert PR link, if any>

2024-06-03 07:23 UTC, keichwa requested changes
cosmetic suggestions

2024-06-03 07:23 UTC, keichwa commented on modules/client-configuration/pages/autoinst-distributions.adoc
> +{productname} use [systemitem]``mgradm`` tool to copy installation file from the source to the server container.
```suggestion
{productname} uses the [systemitem]``mgradm`` tool to copy the installation file from the source to the server container.
```

2024-06-03 07:23 UTC, keichwa commented on modules/client-configuration/pages/autoinst-distributions.adoc
> +. Use [systemitem]``mgradm`` tool to import installation data from the ISO
```suggestion
. Use [command]``mgradm`` to import installation data from the ISO:
```

2024-06-03 07:23 UTC, keichwa commented on modules/client-configuration/pages/autoinst-distributions.adoc
> +  You will need it when you declare the distribution to {productname}.
```suggestion
. Take a note of the distribution path reported by [command]``mgradm``.
  You will need it when you declare the distribution to {productname}.
  
  
```

2024-06-03 07:23 UTC, keichwa commented on modules/client-configuration/pages/autoinst-distributions.adoc
> +[systemitem]``mgradm`` is able to automatically detect distribution name and register it to the server. Provided ISO image needs to contain [path]``.treeinfo`` file.
```suggestion
[systemitem]``mgradm`` is able to automatically detect distribution name and register it to the server.
Provided ISO image needs to contain a [path]``.treeinfo`` file.
```

2024-06-03 07:23 UTC, keichwa commented on modules/client-configuration/pages/autoinst-distributions.adoc
> +. Use [systemitem]``mgradm`` tool
```suggestion
. Use [command]``mgradm``:
```

2024-06-03 07:23 UTC, keichwa commented on modules/client-configuration/pages/autoinst-distributions.adoc
> +. Copy installation files using [systemitem]``mgradm`` tool
```suggestion
. Find the installation files with the command [command]``ls -d /opt/tftpinstall/usr/share/tftpboot-installation/*``.
. Copy installation files using [command]``mgradm``:
```

2024-06-03 07:23 UTC, keichwa commented on modules/client-configuration/pages/autoinst-distributions.adoc
> +. Take a note of the distribution path reported by [systemitem]``mgradm`` tool
```suggestion
. Take a note of the distribution path reported by [systemitem]``mgradm`` tool.
```

2024-06-03 08:48 UTC, 0rnela approved these changes

2024-06-03 12:51 UTC, 0rnela approved these changes

2024-06-04 05:30 UTC, keichwa commented on modules/client-configuration/pages/autoinst-distributions.adoc
> +. Use [command]``mgradm`` to import installation data from the ISO:
```suggestion
. Use [command]``mgradm`` to import installation data from the ISO image:
```

2024-06-04 05:31 UTC, keichwa approved these changes
lgtm

2024-06-05 07:54 UTC, keichwa commented
@aaannz if you do not veto, we'd merge it for you.

2024-06-05 08:38 UTC, aaannz commented
I don't feel like giving my PR a review :) so LGTM and go ahead. I can't merge it myself.

2024-06-05 11:32 UTC, merged