update
uyuni-project/uyuni-docs pull request #3070
Opened 2024-06-07 12:52 UTC by jcayouette

Adds Proxy VM deployment to documentation for 5.0.

2024-06-07 14:15 UTC, 0rnela approved these changes

2024-06-10 06:53 UTC, admd reviewed
Thank you. I have some small suggestions left.

2024-06-10 06:53 UTC, admd commented on modules/installation-and-upgrade/pages/container-deployment/suma/server-deployment-vm-suma.adoc
We should add a note here that raw images preparation https://documentation.suse.com/en-us/sle-micro/5.5/single-html/SLE-Micro-deployment/#sec-raw-preparation and deployment https://documentation.suse.com/en-us/sle-micro/5.5/single-html/SLE-Micro-deployment/#cha-images-procedure and same for the self install images https://documentation.suse.com/en-us/sle-micro/5.5/single-html/SLE-Micro-deployment/#cha-selfinstal-procedure.

We should do this both for the server and proxy docs.

2024-06-10 06:53 UTC, admd commented on modules/installation-and-upgrade/pages/container-deployment/suma/proxy-deployment-vm-suma.adoc
> +Images for {productname} {productnumber} are available at link:https://www.suse.com/download/suse-manager/[{productname} {productnumber} VM images].
We should add an important note here that this preferred way of installation. 

Both for the server and proxy.

2024-06-10 08:27 UTC, keichwa requested changes

2024-06-10 08:27 UTC, keichwa commented on modules/installation-and-upgrade/pages/container-deployment/suma/proxy-deployment-vm-suma.adoc
> +.Procedure: Initial Set Up
```suggestion
.Procedure: Creating Initial Setup
```

2024-06-10 08:27 UTC, keichwa commented on modules/installation-and-upgrade/pages/container-deployment/suma/proxy-deployment-vm-suma.adoc
> +This archive needs to be made available on the Proxy container host.
```suggestion
This archive needs to be made available on the proxy container host.
```

2024-06-10 08:27 UTC, keichwa commented on modules/installation-and-upgrade/pages/container-deployment/suma/proxy-deployment-vm-suma.adoc
> +.Task: Start and Check Proxy Status
```suggestion
.Procedure: Start and Check Proxy Status
```

2024-06-10 08:27 UTC, keichwa commented on modules/installation-and-upgrade/pages/container-deployment/suma/proxy-deployment-vm-suma.adoc
> +=== Using a custom container image for a service
```suggestion
=== Using a Custom Container Image for a Service
```

2024-06-11 08:54 UTC, merged