cleanup following install-proxy-vm.adoc
uyuni-project/uyuni-docs pull request #3097
Opened 2024-06-20 06:42 UTC by keichwa

https://github.com/SUSE/spacewalk/issues/24588

# Some hints

Consider adding an entry to the `CHANGELOG.md` file in the toplevel directory.
Cosmetic changes such as fixing typos do not need log entries (nevertheless it is important to fix typos, etc.)!
In the `manager-4.3`, the hidden `.changelog` file with a leading dot is still in use.

Add Description, Target branches, and related Links below the following section titles.

In the Description, just enter a summary of why you created this PR (and, if available, add any relevant diagram).

# Description

Short summary of why you created this PR (if you added documentation, please add any relevant diagram).

# Target branches

* Which product version this PR applies to (Uyuni, SUMA 4.3, SUMA MU X.Y.Z, or SUMA development version).  This information can be helpful if `ifeval` statements are needed to publish it for certain products only.
* Does this PR need to be backported? If yes, create an issue for tracking it and add the link to this PR.
* Whenever possible, cross-reference each backport PR here, so that all backports can be easily accessed from the description.

Backport targets (edit as needed):

- master
- 4.3

# Links
- This PR tracks issue #<insert spacewalk issue, if any>
- Related development PR #<insert PR link, if any>

2024-06-20 08:06 UTC, 0rnela requested changes

2024-06-20 08:06 UTC, 0rnela commented on modules/installation-and-upgrade/pages/install-vm.adoc
> +It includes {sles} {sles-version} {sp-base} as the underlying operating system and the {productname} software current at the time of build.
```suggestion
They include {sles} {sles-version} {sp-base} as the underlying operating system and the {productname} software current at the time of build.
```

2024-06-20 08:06 UTC, 0rnela commented on modules/installation-and-upgrade/pages/install-vm.adoc
> +=== Set root password using [systemitem]``Ignition``
```suggestion
=== Set Root Password Using [systemitem]``Ignition``
```

2024-06-20 08:06 UTC, 0rnela commented on modules/installation-and-upgrade/pages/install-vm.adoc
> +[systemitem]``Cloud Init`` allows numerous sources where to store configuration data. In this guide we use local iso image with volume id [literal]``cidata`` as a source. The directory structure must
```suggestion
[systemitem]``Cloud Init`` allows numerous sources where to store configuration data. 
In this guide we use local iso image with volume id [literal]``cidata`` as a source. 
The directory structure must look as follows:
```

2024-06-20 08:06 UTC, 0rnela commented on modules/installation-and-upgrade/pages/install-vm.adoc
>  === Set up root password using Cloud Init
```suggestion
=== Set Up Root Password Using Cloud Init
```

2024-06-20 08:06 UTC, 0rnela commented on modules/installation-and-upgrade/pages/install-vm.adoc
> +The command creates a hash of the password you chose. Use this hash as the value of the [literal]``password`` attribute.
```suggestion
The command creates a hash of the password you chose.
Use this hash as the value of the [literal]``password`` attribute.
```

2024-06-20 08:06 UTC, 0rnela commented on modules/installation-and-upgrade/pages/install-vm.adoc
>  == Preparing virtual machine for {productname}
```suggestion
== Preparing Virtual Machine for {productname}
```

2024-06-24 08:02 UTC, jcayouette approved these changes

2024-06-24 08:16 UTC, merged