Updated CLM examples for RHEL9
uyuni-project/uyuni-docs pull request #3112
Opened 2024-06-24 16:55 UTC by cbbayburt

AppStreams sections in CLM examples mention only RHEL8. This PR adds mentions to RHEL9 where applicable.

# Target branches

4.3 only

# Links
- https://github.com/SUSE/spacewalk/issues/24626

2024-06-24 19:49 UTC, mcalmer approved these changes

2024-06-25 04:06 UTC, keichwa requested changes

2024-06-25 04:06 UTC, keichwa commented on modules/administration/pages/content-lifecycle-examples.adoc
>  . Click btn:``Create Filter`` and use these parameters:
```suggestion
. Click btn:[Create Filter] and use these parameters:
```

2024-06-25 04:06 UTC, keichwa commented on .changelog
> +- Updated CLM examples for RHEL 9
```suggestion
- Updated CLM examples for RHEL 9 (bsc#1226687)
```

2024-06-25 11:26 UTC, keichwa approved these changes

2024-06-26 04:40 UTC, merged