Document that transactional-update timer is now disabled by default
uyuni-project/uyuni-docs pull request #3145
Opened 2024-07-02 13:28 UTC by m-czernek

# Description

Documenting changes from https://github.com/SUSE/spacewalk/issues/24251 - we will disable the `transactional-update.timer` by default during the bootstrap process.

# Target branches

* SUMA 5.x and Uyuni for now. 
* We might have to backport the PR to 4.3.x - I'll create an issue after confirming this.

# Links
- This PR tracks issue: https://github.com/SUSE/spacewalk/issues/24251
- Related development PR: https://github.com/uyuni-project/uyuni/pull/8981

2024-07-02 13:46 UTC, keichwa requested changes

2024-07-02 13:46 UTC, keichwa commented on modules/installation-and-upgrade/pages/container-deployment/suma/server-deployment-suma.adoc
> +If you prefer to keep the behavior, enable the timer by running the following command:
```suggestion
If you prefer the {micro} default behavior, enable the timer by running the following command:
```
I think we'd better still assume that the user works with GMC for the first time with suma on Micro.

2024-07-22 13:25 UTC, m-czernek commented
Implemented @keichwa 's comment. I tried to create a backport for 4.3 but I couldn't find the text in the `manager-4.3` - seems like this PR is all we need.

2024-07-23 04:52 UTC, keichwa approved these changes
cosmetic suggestions

2024-07-23 04:52 UTC, keichwa commented on modules/installation-and-upgrade/pages/container-deployment/suma/server-deployment-suma.adoc
> +transactional-update timer during the bootstrap process.
```suggestion
To prevent automatic updates on your server, {productname} disables the transactional-update timer during the bootstrap process.
```

2024-07-23 04:52 UTC, keichwa commented on modules/installation-and-upgrade/pages/container-deployment/suma/server-deployment-suma.adoc
> +If you prefer the {micro} default behavior, enable the timer by running the following command:
```suggestion
If you prefer the {sle-micro} default behavior, enable the timer by running the following command:
```

2024-07-24 11:42 UTC, m-czernek commented
Thanks @keichwa - please merge the PR as you see fit, I don't have the merge permissions.

2024-07-24 13:27 UTC, merged