Fixes in the Admin Guide / SSL certs (re-do of 3011)
uyuni-project/uyuni-docs pull request #3233
Opened 2024-07-30 12:08 UTC by 0rnela

Re-do of https://github.com/uyuni-project/uyuni-docs/pull/3011
(quite old PR, picking up this work resulted with too many conflicts to resolve)

---

- [ ]  mgradm restart

https://github.com/SUSE/spacewalk/issues/24285

2024-07-30 12:10 UTC, 0rnela commented
Changes start in the section "HTTP Strict Transport Security"

[toBeChecked.pdf](https://github.com/user-attachments/files/16427812/toBeChecked.pdf)

2024-07-30 12:12 UTC, cbosdo requested changes

2024-07-30 15:57 UTC, cbosdo approved these changes

2024-07-31 09:34 UTC, jcayouette approved these changes

2024-07-31 12:13 UTC, merged