add links to listings of non-compliant packages
uyuni-project/uyuni-docs pull request #3257
Opened 2024-08-12 13:08 UTC by keichwa

https://github.com/SUSE/spacewalk/issues/25007

# Some hints

Consider adding an entry to the `CHANGELOG.md` file in the toplevel directory.
Cosmetic changes such as fixing typos do not need log entries (nevertheless it is important to fix typos, etc.)!
In the `manager-4.3`, the hidden `.changelog` file with a leading dot is still in use.

Add Description, Target branches, and related Links below the following section titles.

In the Description, just enter a summary of why you created this PR (and, if available, add any relevant diagram).

# Description

Short summary of why you created this PR (if you added documentation, please add any relevant diagram).

# Target branches

* Which product version this PR applies to (Uyuni, SUMA 4.3, SUMA MU X.Y.Z, or SUMA development version).  This information can be helpful if `ifeval` statements are needed to publish it for certain products only.
* Does this PR need to be backported? If yes, create an issue for tracking it and add the link to this PR.
* Whenever possible, cross-reference each backport PR here, so that all backports can be easily accessed from the description.

Backport targets (edit as needed):

- master
- 4.3

# Links
- This PR tracks issue #<insert spacewalk issue, if any>
- Related development PR #<insert PR link, if any>

2024-08-14 09:34 UTC, keichwa commented
Proposal for some rearrangements with "Systems" menu and "Systems Details" tab.  "Systems Details" tab isn't a normal submenu of "Systems" but a hierarchy of its own.  Let's add it at the same level until we will find a even better solution.  Adding screenshots now...
Systems: ![Screenshot from 2024-08-14 11-16-41](https://github.com/user-attachments/assets/a63fe95c-c3ac-44ae-98c9-7add1b0e7f5f)
System Details: ![Screenshot from 2024-08-14 11-17-32](https://github.com/user-attachments/assets/6f7e913d-9faa-43cf-81d3-6779b8324e02)

2024-08-14 10:02 UTC, Bischoff requested changes
lgtm, see nitpicks

2024-08-14 10:02 UTC, Bischoff commented on modules/reference/pages/systems/system-details/sd-details.adoc
> +// FIXME Do we want to display the list here:
hmmm, could be a good idea, but you're the master here...

2024-08-14 10:02 UTC, Bischoff commented on modules/reference/pages/systems/systems-list.adoc
> +These numbers are links to listings of those non-compliant packages per system.
Cool.

Beware: if the number is zero, there's no link, just the number

add ", unless there are no such packages." ?

2024-08-14 10:02 UTC, Bischoff commented on modules/reference/pages/systems/systems-menu.adoc
> +Click the name of a client to go to that client system's the [guimenu]``Details`` overview page and all its tab and subtabs.
cool

2024-08-14 10:02 UTC, Bischoff commented on modules/reference/pages/systems/systems-overview.adoc
> += Systems Menu Entries (Overview)
so true...

2024-08-14 11:44 UTC, keichwa commented on CHANGELOG.md
> +- Restructured documenation of Systems menu and system details tab in
```suggestion
- Restructured documentaion of Systems menu and system details tab in
```

2024-08-14 11:44 UTC, keichwa commented on modules/reference/pages/systems/systems-list.adoc
> +These numbers are links to listings of those non-compliant packages per system.
ok, but I try to think in a positive way:
```suggestion
If there is at least one non-compliant package, you can click the number to display listings of those non-compliant packages per system.
```

2024-08-14 11:44 UTC, keichwa commented on modules/reference/pages/systems/systems-menu.adoc
> +Click the name of a client to go to that client system's the [guimenu]``Details`` overview page and all its tab and subtabs.
```suggestion
Click the name of a client to go to that client system's [guimenu]``Details`` overview page and all its tabs and subtabs.
```

2024-08-14 11:46 UTC, keichwa commented on CHANGELOG.md
> +- Restructured documentaion of Systems menu and system details tab in
```suggestion
- Restructured documentation of Systems menu and system details tab in
```

2024-08-15 09:06 UTC, 0rnela approved these changes

2024-08-19 12:31 UTC, merged