openSUSE Leap Micro as container host
uyuni-project/uyuni-docs pull request #3276
Opened 2024-08-22 13:57 UTC by keichwa

https://github.com/SUSE/spacewalk/issues/25126

# Some hints

Consider adding an entry to the `CHANGELOG.md` file in the toplevel directory.
Cosmetic changes such as fixing typos do not need log entries (nevertheless it is important to fix typos, etc.)!
In the `manager-4.3`, the hidden `.changelog` file with a leading dot is still in use.

Add Description, Target branches, and related Links below the following section titles.

In the Description, just enter a summary of why you created this PR (and, if available, add any relevant diagram).

# Description

Short summary of why you created this PR (if you added documentation, please add any relevant diagram).

# Target branches

* Which product version this PR applies to (Uyuni, SUMA 4.3, SUMA MU X.Y.Z, or SUMA development version).  This information can be helpful if `ifeval` statements are needed to publish it for certain products only.
* Does this PR need to be backported? If yes, create an issue for tracking it and add the link to this PR.
* Whenever possible, cross-reference each backport PR here, so that all backports can be easily accessed from the description.

Backport targets (edit as needed):

- master
- 4.3

# Links
- This PR tracks issue #<insert spacewalk issue, if any>
- Related development PR #<insert PR link, if any>

2024-08-22 16:07 UTC, aaannz requested changes

2024-08-22 16:07 UTC, aaannz commented on modules/installation-and-upgrade/nav-installation-and-upgrade-guide.adoc
> +**** xref:container-deployment/uyuni/proxy-deployment-uyuni.adoc[Deploy on {leap}]
```suggestion
**** xref:container-deployment/uyuni/proxy-deployment-uyuni.adoc[Deploy on {leapmicro}]
```

2024-08-22 16:07 UTC, aaannz commented on modules/installation-and-upgrade/pages/container-deployment/uyuni/proxy-deployment-uyuni.adoc
Please remove those two paths above and only have one path:
```
[path]``/var/lib/containers/storage/volumes``
| Minimum 100 GB, Storage requirements should be calculated for the number of different clients and OS images usage.
```

2024-08-22 16:07 UTC, aaannz commented on modules/installation-and-upgrade/pages/container-deployment/uyuni/proxy-deployment-uyuni.adoc
> +zypper in mgradm mgrctl mgradm-bash-completion mgrctl-bash-completion netavark uyuni-storage-setup-server
```suggestion
zypper in mgrpxy mgrpxy-bash-completion uyuni-storage-setup-proxy
```

2024-08-22 18:17 UTC, keichwa commented
Thanks for reviewing!  Feedback plus minor edits are in HTML is updated (see chained link in description).  More reviews appreciated.  Then I'll merge it tomorrow in the morning.

2024-08-23 09:38 UTC, aaannz approved these changes
👍🏾

2024-08-23 09:43 UTC, merged