info about default contact method and salt bundle vs. minion
uyuni-project/uyuni-docs pull request #3302
Opened 2024-09-05 13:41 UTC by keichwa

https://github.com/SUSE/spacewalk/issues/25121

2024-09-09 12:45 UTC, 0rnela commented on CHANGELOG.md
> +  Guide.
```suggestion
  Guide
```

2024-09-20 08:10 UTC, 0rnela requested changes

2024-09-20 08:10 UTC, 0rnela commented on modules/client-configuration/pages/contact-methods-default.adoc
> +The Default Contact Method is the best scaling method.
```suggestion
The default contact method is the best scaling method.
```

2024-09-20 08:10 UTC, 0rnela commented on modules/client-configuration/pages/contact-methods-intro.adoc
> +Salt Minion ([package]``salt-minion``)::
```suggestion

Salt Minion ([package]``salt-minion``)::
```

2024-09-24 09:36 UTC, srbarrios approved these changes

2024-09-25 09:27 UTC, 0rnela approved these changes

2024-09-27 05:12 UTC, merged