Preventing /etc/krb5.conf and /etc/krb5.keytab being lost after restarting container
uyuni-project/uyuni-docs pull request #3346
Opened 2024-10-02 12:17 UTC by 0rnela

# Description
When restarting the SUMA 5 container,  files /etc/krb5.conf and /etc/krb5.keytab were lost.

Plus, some tidy-up.

# Target branches

Backport targets (edit as needed):

- master
- 5.0

# Links
- This PR tracks issue https://github.com/SUSE/spacewalk/issues/25033

2024-10-02 13:32 UTC, keichwa approved these changes

2024-10-03 04:03 UTC, keichwa requested changes
We need a changelog entry with bsc# reference.

2024-10-04 09:02 UTC, jcayouette approved these changes

2024-10-04 09:02 UTC, jcayouette commented
Changlog added. I will merge for 5.0.2

2024-10-04 09:02 UTC, merged