Update database back and restore procedures using smdba
uyuni-project/uyuni-docs pull request #3348
Opened 2024-10-02 17:15 UTC by rjmateus

# Description

Update the back and restore for database using the smdba tool.

# Target branches

* Which product version this PR applies to (Uyuni, SUMA 4.3, SUMA MU X.Y.Z, or SUMA development version).  This information can be helpful if `ifeval` statements are needed to publish it for certain products only.
* Does this PR need to be backported? If yes, create an issue for tracking it and add the link to this PR.
* Whenever possible, cross-reference each backport PR here, so that all backports can be easily accessed from the description.

Backport targets (edit as needed):

- master
- 5.0

# Links
- This PR tracks issue #<insert spacewalk issue, if any>
- Related development PR #<insert PR link, if any>

2024-10-02 17:15 UTC, rjmateus commented
ping @mbussolotto

2024-10-02 20:16 UTC, keichwa requested changes

2024-10-02 20:16 UTC, keichwa commented on CHANGELOG.md
> +- Update database back and restore procedures using smdba
```suggestion
- Updated database backup and restore procedures using smdba  in Administration
  Guide
```

2024-10-07 09:09 UTC, mbussolotto approved these changes

2024-10-08 07:07 UTC, keichwa approved these changes

2024-10-08 07:07 UTC, keichwa commented on modules/administration/pages/backup-restore.adoc
> +You can check your current database size by running [command]``mgrctl exec "df -h /var/lib/pgsql"``.
```suggestion
You can check your current database size by running:

----
mgrctl exec "df -h /var/lib/pgsql"
----
```

2024-10-08 07:07 UTC, keichwa commented on modules/administration/pages/backup-restore.adoc
> +. Enter in the container terminal
```suggestion
.Procedure: Creating a directory for the backup (do it only once)

. In the container terminal, enter:
```

2024-10-08 07:07 UTC, keichwa commented on modules/administration/pages/backup-restore.adoc
> +As root:
```suggestion
. In your backup location, create a directory for the backup.
  As root, enter:
```

2024-10-08 07:07 UTC, keichwa commented on modules/administration/pages/backup-restore.adoc
> +. Create a system timer file at [path]``/etc/systemd/system/server-db-backup.timer`` with the content:
```suggestion
. Create a systemd timer file at [path]``/etc/systemd/system/server-db-backup.timer`` with the content:
```

2024-10-08 07:07 UTC, keichwa commented on modules/administration/pages/backup-restore.adoc
> +. Enter in the container terminal
```suggestion
. In the container terminal, enter:
```

2024-10-09 05:41 UTC, merged