add admon about package sync
uyuni-project/uyuni-docs pull request #454
Opened 2020-08-19 04:04 UTC by Loquacity

# Description

Adds an admonition explaining that the upstream centos repos don't always match SCC.

# Target branches

Which product version does this PR apply to?

- [ ] Manager-4.0
- [ ] Manager-4.1
- [x] Manager-4.2
- [x] Uyuni

# Links

Fixes https://github.com/SUSE/spacewalk/issues/11870
BZ: https://bugzilla.suse.com/show_bug.cgi?id=1173603

2020-08-19 08:15 UTC, jcayouette approved these changes

2020-08-19 08:55 UTC, mcalmer requested changes

2020-08-19 08:55 UTC, mcalmer commented on modules/client-configuration/pages/clients-centos.adoc
> +Synchronizing with {scc} will install all required packages.
```suggestion
You might notice some disparity in the number of packages available in the Appstream channel between upstream and SUSE Manager Channel.
This is due to the way that {centos} manages their repositories.
{centos} removes older version of packages when a new version was released. SUSE Manager collect all of them.
You will also see different numbers when you compare the same channel added at a different point in time.
```

Feel free to improve :-)

2020-08-19 10:21 UTC, cbbayburt reviewed
Nitpick: At this point I'm not sure if we use the word "Appstream" or "AppStream" (with a capital S) throughout the docs. Please check for consistency.

2020-08-20 02:33 UTC, Loquacity commented
> Nitpick: At this point I'm not sure if we use the word "Appstream" or "AppStream" (with a capital S) throughout the docs. Please check for consistency.

I've used "Appstream" elsewhere. Now I google, though, and discover it probably should be "AppStream". I'll do another PR to fix this.

2020-08-20 04:56 UTC, keichwa approved these changes
did you add some empty lines intentionally?   Or does this your editor proactively?  We'd better avoid this ;)

2020-08-20 05:02 UTC, mcalmer approved these changes
A small suggestion,  but would be good also without it.

2020-08-20 05:02 UTC, mcalmer commented on modules/client-configuration/pages/clients-centos.adoc
> +{centos} removes older version of packages when a new version is released, while {productname} lists all of them, regardless of age.
```suggestion
{centos} removes older version of packages when a new version is released, while {productname} keep all of them, regardless of age.
```

2020-08-20 05:13 UTC, Loquacity commented
> did you add some empty lines intentionally? Or does this your editor proactively? We'd better avoid this ;)

No, that was me getting space happy :wink: I'll back them out.

2020-08-24 02:56 UTC, merged