Fix wrong info
uyuni-project/uyuni-docs pull request #494
Opened 2020-08-29 00:37 UTC by paususe

# Description

- Server hostname rename is supported
- Base OS for Uyuni is Leap 15.2 since 2020.07

# Target branches

Which product version does this PR apply to?

- [ ] Manager-4.0
- [x] Manager-4.1
- [x] Manager-4.2
- [x] Uyuni

# Links

Fixes #<insert issue or PR link, if any>

2020-08-31 00:54 UTC, Loquacity requested changes

2020-08-31 00:54 UTC, Loquacity commented on modules/installation/pages/network-requirements.adoc
> +Although changing the server name is possible and supported, such a change would need to be planned for and coordinated since all clients need to to be made aware of that.
```suggestion
Although changing the server name is possible and supported, it is important to plan for this change before going ahead with it.
When you change the hostname of the server, all clients attached to the server must be made aware of the change.
```

Fixing the run-on sentence.

2020-08-31 07:37 UTC, keichwa approved these changes

2020-09-01 06:59 UTC, jcayouette approved these changes
After suggest changes by Lana looks good!

2020-09-02 14:01 UTC, merged