Retail cleanup #12215 keichwa
uyuni-project/uyuni-docs pull request #537
Opened 2020-09-15 08:40 UTC by keichwa

# Description

General cleanup

# Target branches

Which product version does this PR apply to?

- [ ] Manager-4.0
- [ ] Manager-4.1
- [x] Manager-4.2
- [x] Uyuni

# Links

Fixes https://github.com/SUSE/spacewalk/issues/12215

2020-09-15 19:44 UTC, keichwa commented on modules/retail/pages/retail-install-setup.adoc
> +// 2020-08-27, ke: We mustsettle on one term: "POS images" or "terminal images"
```suggestion
// 2020-08-27, ke: We must settle on one term: "POS images" or "terminal images"
```

2020-09-17 12:07 UTC, keichwa commented
@aaannz in `retail-mass-config.adoc`, we seem to do mass configuration with branch servers twice.  Can you check it?  See the FIXME statements within the file.

2020-09-21 01:55 UTC, Loquacity approved these changes

2020-09-21 01:55 UTC, Loquacity requested changes
Revoking my approval, you have broken xrefs.

2020-09-21 07:04 UTC, keichwa commented
> Revoking my approval, you have broken xrefs.

Thanks for spotting.  Additionally I found sth different :)  Please re-tick.

2020-09-21 23:47 UTC, Loquacity approved these changes

2020-09-22 08:56 UTC, merged