Fix code block indentation in 4.0 Monitoring Docs
uyuni-project/uyuni-docs pull request #541
Opened 2020-09-17 00:05 UTC by Loquacity

# Description

***This is for 4.0 docs only***

Reported by a supporter via email:

```
https://documentation.suse.com/external-tree/en-us/suma/4.0/suse-manager/administration/monitoring.html

job_name: 'suma'
uyuni_sd_configs:
host: "http://your-suse-manager-server-url"
username: "apiuser"
password: "password"

That block should be:

job_name: 'suma'
uyuni_sd_configs:
- host: "http://your-suse-manager-server-url"
  username: "apiuser"
  password: "password"
```
Investigation shows that this procedure exists only in the 4.0 docs, the 4.1 docs have this as part of a larger procedure. There were a couple of errors other than the indentation:

![image](https://user-images.githubusercontent.com/3914967/93404199-ea87b300-f8cc-11ea-833a-f05aafbe41e1.png)

This PR fixes:
* Adds a new heading and a short stem sentence. This extracts the procedure title from the admonition block.
* Gerundizes the procedure title
* Fixes the reported code indentation issue (I double checked with how it's written in 4.1, too).

# Target branches

Which product version does this PR apply to?

- [x] Manager-4.0
- [ ] Manager-4.1
- [ ] Manager-4.2
- [ ] Uyuni

# Links

Fixes #<insert issue or PR link, if any>

2020-09-17 00:17 UTC, Loquacity commented
With fix applied:
![image](https://user-images.githubusercontent.com/3914967/93404955-fffddc80-f8ce-11ea-94bf-2f8bdcdd645a.png)

2020-09-17 05:15 UTC, keichwa approved these changes

2020-09-17 08:05 UTC, witekest requested changes
Provided configuration fix is correct.

2020-09-17 08:05 UTC, witekest commented on modules/administration/pages/monitoring.adoc
> +You can enable service discovery to allow Prometheus to watch a host URL.
```suggestion
You can enable service discovery to allow Prometheus to automatically configure monitored minions.
```

2020-09-20 21:22 UTC, cavalheiro approved these changes

2020-09-21 02:03 UTC, merged

2020-10-30 18:51 UTC, willianops commented
for me, the problem not solved with indentation


  FAILED: parsing YAML file prometheus.yml: yaml: unmarshal errors:
  line 45: field uyuni_sd_configs not found in type config.plain

2020-11-02 01:02 UTC, Loquacity commented
> for me, the problem not solved with indentation
> 
> FAILED: parsing YAML file prometheus.yml: yaml: unmarshal errors:
> line 45: field uyuni_sd_configs not found in type config.plain

Hi, if you work out what the problem is, let us know in a new issue and we'll update the docs accordingly.