changed the default of bootstrap_repo_flush to off
uyuni-project/uyuni-docs pull request #597
Opened 2020-10-09 13:00 UTC by mcalmer

# Description

Currently the default for bootstrap_repo_flush is "on". This creates some problems and we change it to "off".
The docs must adapt.

# Target branches

Which product version does this PR apply to?

- [x] Manager-4.1
- [x] Manager-4.2
- [x] Uyuni

# Links

PRs which change the option:

2020-10-12 00:37 UTC, Loquacity requested changes

2020-10-12 00:37 UTC, Loquacity commented on modules/client-configuration/pages/bootstrap-repository.adoc
> +By default, an exiting repository is only updated with the latest packages.
```suggestion
By default, existing repositories are updated only with the latest packages.
```

2020-10-12 00:37 UTC, Loquacity commented on modules/client-configuration/pages/bootstrap-repository.adoc
> +It can be configured to always start with an empty repository.
```suggestion
You can configure it to always start with an empty repository instead.
```

2020-10-12 00:37 UTC, Loquacity commented on modules/client-configuration/pages/bootstrap-repository.adoc
> +When the ``flush`` option is enabled, and you attempt to generate the bootstrap repository for multiple architectures, only one architecture would be generated.
```suggestion
When the ``flush`` option is enabled, and you attempt to generate the bootstrap repository for multiple architectures, only one architecture is generated.
```

2020-10-13 00:55 UTC, Loquacity approved these changes

2020-10-13 07:36 UTC, jcayouette approved these changes

2020-10-13 23:30 UTC, merged

2020-10-13 23:33 UTC, Loquacity commented
:heavy_check_mark: Backported to `manager-4.1`