Mbrookhuis ssh push init 2
uyuni-project/uyuni-docs pull request #622
Opened 2020-10-20 07:32 UTC by mbrookhuis

# Description

Short summary of why you created this PR

# Target branches

Which product version does this PR apply to?

- [*] Manager-4.0
- [*] Manager-4.1
- [ ] Manager-4.2
- [*] Uyuni

# Links

Fixes #<insert issue or PR link, if any>

2020-10-21 00:32 UTC, Loquacity requested changes

2020-10-21 00:32 UTC, Loquacity commented on modules/client-configuration/pages/contact-methods-pushssh.adoc
> +OPTIONAL: When [command]``ssh_push_sudo_user`` has been defined, add the option [command]``--notty``. This will allow the administrator to enter the ``root`` password.
```suggestion
. OPTIONAL: When you have defined [command]``ssh_push_sudo_user``, you can allow use of the root password by adding the [command]``--notty`` option.
```

2020-10-21 00:32 UTC, Loquacity commented on modules/client-configuration/pages/contact-methods-pushssh.adoc
> +OPTIONAL: When [command]``ssh_push_sudo_user`` has been defined, add the option [command]``--notty``. This will allow the administrator to enter the ``root`` password.
This makes it its own step, rather than tacking it on the previous one, and rewords it to be more active.

2020-10-21 11:02 UTC, keichwa approved these changes

2020-10-22 00:33 UTC, Loquacity approved these changes

2020-10-22 00:33 UTC, merged