Add Redfish to Power Management
uyuni-project/uyuni-docs pull request #629
Opened 2020-10-23 04:56 UTC by Loquacity

# Description

Add Redfish protocol to power management chapter in client cfg, and update Ref Guide in SD-Provisioning.

# Target branches

Which product version does this PR apply to?

- [ ] Manager-4.0
- [ ] Manager-4.1
- [x] Manager-4.2
- [x] Uyuni

# Links

Fixes https://github.com/SUSE/spacewalk/issues/12767

2020-10-23 05:04 UTC, Loquacity commented
@mcalmer in the webui, it basically says that Redfish isn't supported. Does this need to be changed?

![image](https://user-images.githubusercontent.com/3914967/96958529-10921a00-1541-11eb-85e8-d5b16f6ad03a.png)

2020-10-23 05:37 UTC, mcalmer commented
> @mcalmer in the webui, it basically says that Redfish isn't supported. Does this need to be changed?
> 
> ![image](https://user-images.githubusercontent.com/3914967/96958529-10921a00-1541-11eb-85e8-d5b16f6ad03a.png)

Good catch. I have to change that message.

2020-10-23 08:00 UTC, mcalmer commented
> > @mcalmer in the webui, it basically says that Redfish isn't supported. Does this need to be changed?
> > ![image](https://user-images.githubusercontent.com/3914967/96958529-10921a00-1541-11eb-85e8-d5b16f6ad03a.png)
> 
> Good catch. I have to change that message.

What about the following text:

    By default only the tested and supported power management types are listed, but others may work. To enable other power 
    management types override the "java.power_management.types" option in rhn.conf.

2020-10-23 09:07 UTC, Loquacity commented
> 
> ```
> By default only the tested and supported power management types are listed, but others may work. To enable other power 
> management types override the "java.power_management.types" option in rhn.conf.
> ```

```
The power management types listed are tested and supported, but other types might work. To enable other power management types edit the "java.power_management.types" option in rhn.conf.
 ```

2020-10-23 09:12 UTC, mcalmer commented
> > ```
> > By default only the tested and supported power management types are listed, but others may work. To enable other power 
> > management types override the "java.power_management.types" option in rhn.conf.
> > ```
> 
> ```
> The power management types listed are tested and supported, but other types might work. To enable other power 
> management types edit the "java.power_management.types" option in rhn.conf.
> ```

As soon as you modify the var, the types are also listed. But I hope we can ignore this detail and nobody will demand for support when they add a new type and it does not work.

2020-10-23 11:46 UTC, mcalmer requested changes
Added some suggestions.

Mainly Power Management is not only a protocol which you can install on the client.
It is a separate mini computer which control the main server. It has an own IP address, OS and hardware. It is called "Controller" and I think this makes it better understandable to talk about the controller instead of a protocol.

2020-10-23 11:46 UTC, mcalmer commented on modules/client-configuration/pages/power-management.adoc
> +The selected client must have the protocol enabled, and be configured to use a power management server.
```suggestion
The selected client must have a power management controller supporting one of these protocols.
```

2020-10-23 11:46 UTC, mcalmer commented on modules/client-configuration/pages/power-management.adoc
> +For Redfish, ensure you have a valid SSL connection between the client and the {productname} Server.
```suggestion
For Redfish, ensure you can establish a valid SSL connection between the client and the {productname} Server.
```

2020-10-23 11:46 UTC, mcalmer commented on modules/reference/pages/systems/system-details/sd-provisioning.adoc
> +The selected client must have the protocol enabled, and be configured to use a power management server.
```suggestion
The selected client must have a power management controller supporting one of these protocols
```

2020-10-23 11:46 UTC, mcalmer commented on modules/reference/pages/systems/system-details/sd-provisioning.adoc
> +For Redfish, ensure you have a valid SSL connection between the client and the {productname} Server.
```suggestion
For Redfish, ensure you can establish a valid SSL connection between the client and the {productname} Server.
```

2020-10-26 06:46 UTC, keichwa approved these changes

2020-10-26 06:46 UTC, keichwa commented on modules/reference/pages/systems/system-details/sd-provisioning.adoc
> +The selected client must have a power management controller supporting one of these protocols
```suggestion
The selected client must have a power management controller supporting one of these protocols.
```

2020-10-26 08:11 UTC, mcalmer approved these changes

2020-10-26 23:37 UTC, merged