Add pub_hwm and zmq_backlog to the tuning guide
uyuni-project/uyuni-docs pull request #632
Opened 2020-10-23 11:19 UTC by moio

# Description

Add pub_hwm and zmq_backlog knobs to the tuning guide.

# Target branches

Which product version does this PR apply to?

- [ ] Manager-4.0
- [x] Manager-4.1
- [x] Manager-4.2
- [x] Uyuni

# Links

part of https://github.com/SUSE/spacewalk/issues/11954

2020-10-23 11:20 UTC, moio commented
FYI: @rjmateus @meaksh @vzhestkov

2020-10-26 01:16 UTC, Loquacity requested changes
minor edits for future tense

2020-10-26 01:16 UTC, Loquacity commented on modules/large-deployments/pages/tuning.adoc
> +| Description          | The maximum number of outstanding messages sent by `salt-master`. If more than this number of messages need to be sent concurrently, communication with clients will slow down
```suggestion
| Description          | The maximum number of outstanding messages sent by `salt-master`. If more than this number of messages need to be sent concurrently, communication with clients slows down, potentially resulting in timeout errors during load peaks.
```

2020-10-26 01:16 UTC, Loquacity commented on modules/large-deployments/pages/tuning.adoc
> +| Description          | The maximum number of allowed client connections that have started but not concluded the opening process. If more than this number of clients connects in a very short time fr
```suggestion
| Description          | The maximum number of allowed client connections that have started but not concluded the opening process. If more than this number of clients connects in a very short time frame, connections are dropped and clients experience a delay re-connecting.
```

2020-10-26 08:14 UTC, keichwa approved these changes

2020-10-26 08:14 UTC, keichwa commented on modules/large-deployments/pages/tuning.adoc
> +| Tune when            | xref:client-count[Client count] increases significantly and `Salt request timed out. The master is not responding` errors appear when pinging minions during a load peak.
```suggestion
| Tune when            | xref:client-count[Client count] increases significantly and ``Salt request timed out. The master is not responding.`` errors appear when pinging minions during a load peak.
```
I think single tics don't work with adoc.  If yes, we must adjust it later on, too.
We usually call minions "clients".  I'm not sure whether we want to do the same here.

2020-10-26 23:38 UTC, Loquacity approved these changes

2020-10-26 23:38 UTC, merged