EPEL section
uyuni-project/uyuni-docs pull request #647
Opened 2020-10-29 01:06 UTC by Loquacity

# Description

The AppStream section conflated AppStream with EPEL.

# Target branches

Which product version does this PR apply to?

- [ ] Manager-4.0
- [ ] Manager-4.1
- [x] Manager-4.2
- [x] Uyuni

# Links

Reference: https://github.com/uyuni-project/uyuni-docs/pull/643#pullrequestreview-518447067

2020-10-29 05:16 UTC, keichwa approved these changes

2020-10-29 09:24 UTC, paususe requested changes
Please split this in two separate sections: one for EPEL, one for appstreams. In the appstreams one, please mention there are specific CLM filters for appstreams and refer to https://www.uyuni-project.org/uyuni-docs/uyuni/administration/content-lifecycle-examples.html#_appstream_filters

2020-10-29 11:32 UTC, jcayouette approved these changes

2020-10-30 10:07 UTC, paususe approved these changes
LGTM

2020-11-02 00:59 UTC, merged