using reactivation keys;
uyuni-project/uyuni-docs pull request #718
Opened 2020-12-02 16:20 UTC by keichwa

# Description

Using reactivation key with bootstrap script.

# Target branches

Which documentation version does this PR apply to?

- [x] Master (Default)
- [ ] Manager-4.1
- [ ] Manager-4.0

# Links

Fixes https://github.com/SUSE/spacewalk/issues/13320

2020-12-02 17:03 UTC, mcalmer requested changes
I would also write quickly how to use re-activation keys with salt.
It is about setting a grain on the minion in /etc/salt/minion.d/susemanager.conf.

```
grains:
    susemanager:
        management_key: <reactivation-key>
```

2020-12-03 09:23 UTC, keichwa commented
> I would also write quickly how to use re-activation keys with salt.

thanks, this is a good idea.  Please recheck!

2020-12-03 10:08 UTC, Loquacity commented on modules/client-configuration/pages/activation-keys.adoc
> +With Salt, you set a grain on the Salt client in [path]``/etc/salt/minion.d/susemanager.conf``:
```suggestion
For Salt clients, set a grain in [path]``/etc/salt/minion.d/susemanager.conf``:
```

2020-12-03 10:11 UTC, Loquacity requested changes

2020-12-03 10:11 UTC, Loquacity commented on modules/client-configuration/pages/activation-keys.adoc
> +Only on traditional clients you can combine reactivation keys with activation keys to aggregate the settings of multiple keys for a single system profile.
```suggestion
On traditional clients, you can combine reactivation keys with activation keys to aggregate the settings of multiple keys for a single system profile.
```

2020-12-03 10:11 UTC, Loquacity commented on modules/client-configuration/pages/activation-keys.adoc
> +With Salt, you set a grain on the Salt client in [path]``/etc/salt/minion.d/susemanager.conf``:
```suggestion
For Salt clients, set a grain in [path]``/etc/salt/minion.d/susemanager.conf``:
```

2020-12-04 06:22 UTC, Loquacity approved these changes

2020-12-07 07:01 UTC, keichwa commented
I resolved a conflict.  I hope now nothing is lost nor duplicated.

2020-12-07 10:05 UTC, Loquacity requested changes

2020-12-07 10:05 UTC, Loquacity commented on modules/client-configuration/pages/activation-keys.adoc
> +For Salt clients, after you have created a reactivation key, you can use it as the ``management_key`` grain in [path]``/etc/salt/minion.d/susemanager.conf``. For example:
```suggestion
For Salt clients, after you have created a reactivation key, you can use it as the ``management_key`` grain in [path]``/etc/salt/minion.d/susemanager.conf``. 
For example:
```

2020-12-07 10:05 UTC, Loquacity commented on modules/client-configuration/pages/activation-keys.adoc
> +You can now restart the [command]``salt-minion`` to apply the reactivation key.
```suggestion
Restart the [command]``salt-minion`` process to apply the reactivation key.
```

??

2020-12-07 12:40 UTC, keichwa commented on modules/client-configuration/pages/activation-keys.adoc
> +For Salt clients, after you have created a reactivation key, you can use it as the ``management_key`` grain in [path]``/etc/salt/minion.d/susemanager.conf``. For example:
by the time, this is already in.

2020-12-08 01:06 UTC, Loquacity approved these changes

2020-12-08 06:37 UTC, merged