BACKPORT 4.1: Debian 9 & 10 on SUMA (#684)
uyuni-project/uyuni-docs pull request #729
Opened 2020-12-09 04:13 UTC by Loquacity

* debian suma setup

* changelog

* product/channel names

# Description

Short summary of why you created this PR

# Target branches

Which documentation version does this PR apply to?

- [ ] Master (Default)
- [x] Manager-4.1
- [ ] Manager-4.0

# Links

Fixes #<insert issue or PR link, if any>

2020-12-09 06:31 UTC, keichwa approved these changes

2020-12-09 08:23 UTC, mcalmer requested changes
I think this can be done better. I do not have an up to date version of SUMA 4.1 docs to compare Ubuntu 20.04. But I think we described it there a bit different. Please check

2020-12-09 08:23 UTC, mcalmer commented on modules/client-configuration/pages/clients-debian.adoc
> +| {debian} 10 | SUSE Linux Enterprise Client Tools Debian 10 amd64
The Client Tools are just a child product. Please check how you described Ubuntu 20.04. Both Debian versions are setup the same way.

2020-12-09 09:31 UTC, jcayouette approved these changes

2020-12-10 00:18 UTC, Loquacity commented
Hey Michael, this is a backport so let's not make changes here. I'll merge this one, and make a note to take another look when I get back from leave.

2020-12-10 00:18 UTC, Loquacity commented
> I think this can be done better. I do not have an up to date version of SUMA 4.1 docs to compare Ubuntu 20.04. But I think we described it there a bit different. Please check

Hey Michael, this is a backport so let's not make changes here. I'll merge this one, and make a note to take another look when I get back from leave.

2020-12-10 00:20 UTC, merged