Salt manager #13389 keichwa
uyuni-project/uyuni-docs pull request #747
Opened 2020-12-22 07:42 UTC by keichwa

# Description

Merge fragments about /srv/susemanager/salt/

# Target branches

Which documentation version does this PR apply to?

- [x] Master (Default)
- [ ] Manager-4.1
- [ ] Manager-4.0

# Links

Fixes #<insert issue or PR link, if any>
https://github.com/SUSE/spacewalk/issues/13389

2020-12-22 12:57 UTC, Bischoff reviewed
It looks good to me, but could a developer specialist of Salt states please have a look? I really do not feel comfortable enough with the topic to approve.

2021-01-04 01:53 UTC, Loquacity requested changes

2021-01-04 01:53 UTC, Loquacity commented on .changelog
> +- Salt states chapter in Salt Guide for clarity (bsc#1179692)
```suggestion
- Edited Salt states chapter in Salt Guide for clarity (bsc#1179692)
```

2021-01-04 01:53 UTC, Loquacity commented on modules/salt/nav-salt-guide.adoc
> +** xref:salt-states.adoc[Salt States and Pilars]
```suggestion
** xref:salt-states.adoc[Salt States and Pillars]
```

2021-01-04 01:53 UTC, Loquacity commented on modules/salt/pages/salt-states.adoc
> += Salt States and Pilars
```suggestion
= Salt States and Pillars
```

2021-01-04 01:53 UTC, Loquacity commented on modules/salt/pages/salt-states.adoc
> +In these examples we will use an example Group ID of [systemitem]``GID``.
```suggestion
These examples use an example Group ID of [systemitem]``GID``.
```

2021-01-04 09:57 UTC, keichwa commented
@brejoc can you please review this change--you are our Salt expert :)

2021-01-04 10:16 UTC, mcalmer commented on modules/salt/pages/salt-file-locations.adoc
> +├── manager_org_DEVEL
```suggestion
├── manager_org_<org id>
```

The organization ID was used, not the name.

2021-01-11 01:05 UTC, Loquacity approved these changes

2021-01-11 08:21 UTC, merged