Salt Client registration from Command Line
uyuni-project/uyuni-docs pull request #765
Opened 2021-01-12 10:11 UTC by keichwa

https://github.com/SUSE/spacewalk/issues/13366

# Description

Initiat registration from Client (Salt)

# Target branches

Which documentation version does this PR apply to?

- [x] Master (Default)
- [ ] Manager-4.1
- [ ] Manager-4.0

# Links

Fixes https://github.com/SUSE/spacewalk/issues/13366

2021-01-12 10:12 UTC, keichwa commented
@paususe I guess this is what you asked for.

And @Loquacity do we want to have this backported to 4.1?

2021-01-13 01:06 UTC, Loquacity commented
> And @Loquacity do we want to have this backported to 4.1?

Yes, let's, but wait until we unfreeze the repo (should be later this week).

2021-01-15 01:42 UTC, Loquacity requested changes

2021-01-15 01:42 UTC, Loquacity commented on modules/client-configuration/pages/registration-cli.adoc
> +This method operates using ports 4505 and 4506 inbound to the server.
```suggestion
This method uses ports 4505 and 4506 inbound to the server.
```

2021-01-15 01:42 UTC, Loquacity commented on modules/client-configuration/pages/registration-cli.adoc
> +This procedure requires that you have installed the Salt package on the Salt client before registration ([package]``salt-minion``).
```suggestion
This procedure requires that you have installed the [package]``salt-minion`` package on the Salt client before registration.
```

2021-01-15 01:42 UTC, Loquacity commented on modules/client-configuration/pages/registration-cli.adoc
> +. Add or edit the FQDN of the {productname} Server or of the Proxy as the `master`, and the activation key, to the client configuration file:
```suggestion
. Add or edit the FQDN of the {productname} Server or of the Proxy as the `master`, and add the activation key to the client configuration file:
```

??

2021-01-27 01:15 UTC, Loquacity approved these changes

2021-01-27 08:16 UTC, merged

2021-01-27 08:16 UTC, keichwa commented
And then I'll create a 4.1 backport.