explain autoinstallation with SP2 Installer Media using extra options
uyuni-project/uyuni-docs pull request #879
Opened 2021-03-31 08:12 UTC by mcalmer

# Description

Starting with SLE 15 SP2 some extra options are required to be set when doing an autoinstallation using the Installer Media.
This is missing in the docs.

# Target branches

Which documentation version does this PR apply to?

- [x] Master (Default)
- [x] Manager-4.1
- [x] Manager-4.0

# Links

See also https://bugzilla.suse.com/show_bug.cgi?id=1183953

2021-04-01 00:31 UTC, Loquacity requested changes

2021-04-01 00:31 UTC, Loquacity commented on modules/client-configuration/pages/autoinst-setup.adoc
> +This is not required when the Full media is used.
```suggestion
If you are installing {sle}{nbsp}15{nbsp}SP2 or later using the unified installer, you need to set additional kernel options.
In the [guimenu]``Kernel Options`` field, add ``useonlinerepo``.
Additionally, if you are not using your own GPG key, add the ``insecure=1`` kernel parameter.

This is not required if you are performing an installation from the full DVD.
```

2021-04-01 08:27 UTC, keichwa approved these changes

2021-04-06 01:12 UTC, Loquacity approved these changes

2021-04-07 08:33 UTC, merged

2021-04-08 01:28 UTC, Loquacity commented
:heavy_check_mark: 4.1: https://github.com/uyuni-project/uyuni-docs/pull/884
:heavy_check_mark: 4.0: https://github.com/uyuni-project/uyuni-docs/pull/885