Update disconnected-setup.adoc
uyuni-project/uyuni-docs pull request #882
Opened 2021-04-06 09:08 UTC by thsnielsen

Was asked to pull against master branch - i hope i got it right this time - note to self : go see some training on git ;-)

# Description

Short summary of why you created this PR

# Target branches

Which documentation version does this PR apply to?

- [ ] Master (Default)
- [ ] Manager-4.1
- [ ] Manager-4.0

# Links

Fixes #<insert issue or PR link, if any>

2021-04-08 01:33 UTC, Loquacity requested changes

2021-04-08 01:33 UTC, Loquacity commented on modules/administration/pages/disconnected-setup.adoc
> +----
```suggestion
----
rmt-cli export settings /mnt/usb
rmt-cli export repos /mnt/usb
----
```

2021-04-08 01:37 UTC, Loquacity commented
Much better, thank you! Just a quick suggestion for the adoc syntax. For the record, you don't always need to create a new PR to change the branch, in most cases you can hit the Edit button next to the title, and then adjust the branch directly in the GH Web UI:

![image](https://user-images.githubusercontent.com/3914967/113955229-aa832000-985e-11eb-8487-80fccd1bbc7c.png)
![image](https://user-images.githubusercontent.com/3914967/113955276-bff84a00-985e-11eb-81ab-208f4665c473.png)

2021-04-08 09:09 UTC, keichwa approved these changes

2021-04-12 01:44 UTC, merged

2021-04-12 01:46 UTC, Loquacity commented
:heavy_check_mark: Backport 4.1: https://github.com/uyuni-project/uyuni-docs/pull/892