Fixes for Amazon Linux 2
uyuni-project/uyuni-docs pull request #883
Opened 2021-04-06 15:01 UTC by juliogonzalez

# Description

Fixes for Amazon Linux 2:

- Channel names where incorrect after a wrong `sed` I called to rename the entity from `amazonlinux` to `amazon`
- Traditional is not supported

# Target branches

Which documentation version does this PR apply to?

- [x] Master (Default)
- [ ] Manager-4.1
- [ ] Manager-4.0

# Links

None. Notified by @paususe. Thanks!

2021-04-06 15:11 UTC, paususe approved these changes
LGTM

Maybe add the same note about the traditional stack I added to Alibaba?

2021-04-07 15:43 UTC, juliogonzalez commented
> Maybe add the same note about the traditional stack I added to Alibaba?

Done.

@Loquacity please review, and merge if you are OK with the PR.

2021-04-08 01:31 UTC, Loquacity requested changes

2021-04-08 01:31 UTC, Loquacity commented on modules/client-configuration/pages/supported-features-amazon.adoc
> +{star} The traditional stack is available on {alibabaclo} but it is unsupported.
```suggestion
{star} The traditional stack is available on {amazon} but it is unsupported.
```

2021-04-09 00:56 UTC, Loquacity approved these changes

2021-04-09 00:57 UTC, merged