In Supported Clients Table of Client ConfigGuide list Debian 10 and 9
uyuni-project/uyuni-docs pull request #973
Opened 2021-05-25 15:57 UTC by keichwa

# Description

Cf. https://github.com/uyuni-project/uyuni-docs/issues/848

# Target branches

Which documentation version does this PR apply to?

- [x] Master (Default)
- [x] Manager-4.2
- [x] Manager-4.1
- [ ] Manager-4.0

# Links

Fixes #<insert issue or PR link, if any>

2021-05-25 16:03 UTC, juliogonzalez approved these changes
Ok, if the other tables contain Debian as well (I think the they did, but I'd suggest you check, just in case).

Then backport to 4.1, as this was reported there as well (FMPOV we should prepare a resubmission for 4.1.8 with this)

2021-05-25 16:06 UTC, juliogonzalez requested changes
I think you will need https://bugzilla.suse.com/show_bug.cgi?id=1186427 at the changelog.

2021-05-26 06:16 UTC, keichwa commented on .changelog
> +Debian 10 and 9 unconditionally (also in the context of SUSE Manager)
```suggestion
Debian 10 and 9 unconditionally also in the context of SUSE Manager
(bsc#1186427)
```

2021-05-26 08:05 UTC, juliogonzalez reviewed
Ok, if the other tables contain Debian as well (I think the they did, but I'd suggest you check, just in case).

Then backport to 4.1, as this was reported there as well (FMPOV we should prepare a resubmission for 4.1.8 with this)

2021-05-26 08:26 UTC, merged

2021-05-26 08:43 UTC, keichwa commented
> Then backport to 4.1, as this was reported there as well (FMPOV we should prepare a resubmission for 4.1.8 with this)

I think a resubmission because of an outdated support table is not need.  I guess and hope the release notes and marketing product info are up-to-date. At least, I already files a backport PR for `manager-4.1`.